#pragma once
#include <cstdint>
enum class ErrorCode : uint32_t {
  kOk,
  kUnknown,
  kTcpServerStartFailed,
  kTcpServerAcceptFailed,
  kMavlinkInitFailed,
  kFcLinkInitFailed,
  kCommandInitFailed,
  kLedGpioConfigFailed,
  kLedTimerInitFailed,
  kLedChannelInitFailed,
  kLedFadeInstallFailed,
  kButtonGpioConfigFailed,
  kWifiNvsInitFailed,
  kWifiNetifInitFailed,
  kWifiEventLoopFailed,
  kWifiInitFailed,
  kWifiSetStorageFailed,
  kUartParamConfigFailed,
  kUartSetPinFailed,
  kUartDriverInstallFailed,
  kUartInvalidNumber,
  kProgrammerUartNull,
  kStm32GpioInitFailed,
  kButtonReinit,
  kLedReinit,
  kGpioReinit,
  kGpioInvalidPort,
  kTcpServerError,
  kM9nNotResponding,
  kM9nConfigProtocolFailed,
  kM9nConfigNavPvtFailed,
  kM9nConfigNavDopFailed,
  kM9nConfigNavCovFailed,
  kM9nConfigNavEoeFailed,
  kM9nConfigRateFailed,
  kM9nConfigDynModelFailed,
  kM9nConfigConstellationFailed,
  kM9nConfigItfmFailed,
  kM9nConfigTimepulseFailed,
  kM9nConfigTimepulseBufferError,
  // Verification failures
  kM9nVerifyProtocolFailed,
  kM9nVerifyNavPvtFailed,
  kM9nVerifyNavDopFailed,
  kM9nVerifyNavCovFailed,
  kM9nVerifyNavEoeFailed,
  kM9nVerifyRateFailed,
  kM9nVerifyDynModelFailed,
  kM9nVerifyConstellationFailed,
  kM9nVerifyItfmFailed,
  kM9nVerifyTimepulseFailed,
  kImuWhoAmIFail,
  kImuFifoUnsupported,
  kImuFifoReadTooLarge,
  kImuOverrun,
  kImuDroppedFrame,
  kImuInvalidOdr,
  kImuOdrMismatch,
  kImuNotInitialized,
  kImuDmaBufferTooSmall,
  kImuInvalidSampleDetected,
  kInvalidFifoWatermarkRecords,
};

const char *GetMessage(ErrorCode code);
