#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

#include "packed_bitmap.hpp"

// Generated by tools/png_conv.py from am32.png
namespace am32_bitmap {

inline constexpr std::size_t kVisibleWidth = 18;
inline constexpr std::size_t kVisibleHeight = 18;
inline constexpr std::size_t kCanvasWidth = 18;
inline constexpr std::size_t kCanvasHeight = 24;
inline constexpr std::size_t kOffsetX = 0;
inline constexpr std::size_t kOffsetY = 0;
inline constexpr std::size_t kVisiblePageCount = 3;
inline constexpr std::array<std::uint8_t, 54> kBitmapData = {
    0x10, 0x38, 0xF0, 0xE2, 0x07, 0x0E, 0xCC, 0xCC, 0x0C, 0xCC, 0xCC,
    0xCC, 0x0E, 0x07, 0xE2, 0xF0, 0x38, 0x10, 0x20, 0x70, 0x3F, 0x1F,
    0x80, 0xC0, 0xC0, 0xCC, 0xC0, 0xC0, 0xCC, 0xC0, 0xC0, 0x80, 0x1F,
    0x3F, 0x70, 0x20, 0x00, 0x00, 0x00, 0x01, 0x03, 0x01, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x01, 0x03, 0x01, 0x00, 0x00, 0x00,
};

// Draw through this, not the parts: a call site that restates the dimensions
// can restate them wrongly, and nothing downstream would notice.
inline constexpr PackedBitmap kBitmap{kBitmapData, kVisibleWidth,
                                      kVisibleHeight};
static_assert(kBitmap.Valid(), "packed data too small for its dimensions");

}  // namespace am32_bitmap
