#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

#include "packed_bitmap.hpp"

// Generated by tools/png_conv.py from sd_card.png
namespace sd_card_bitmap {

inline constexpr std::size_t kVisibleWidth = 18;
inline constexpr std::size_t kVisibleHeight = 18;
inline constexpr std::size_t kCanvasWidth = 18;
inline constexpr std::size_t kCanvasHeight = 24;
inline constexpr std::size_t kOffsetX = 0;
inline constexpr std::size_t kOffsetY = 0;
inline constexpr std::size_t kVisiblePageCount = 3;
inline constexpr std::array<std::uint8_t, 54> kBitmapData = {
    0x00, 0xC0, 0x60, 0x3F, 0x01, 0x0D, 0x0D, 0x01, 0x01, 0x1D, 0x01, 0x01,
    0x0D, 0x0D, 0x01, 0xFF, 0x00, 0x00, 0x00, 0xF3, 0x0E, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00,
    0x00, 0x03, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02, 0x02,
    0x02, 0x02, 0x02, 0x03, 0x00, 0x00,
};

// Draw through this, not the parts: a call site that restates the dimensions
// can restate them wrongly, and nothing downstream would notice.
inline constexpr PackedBitmap kBitmap{kBitmapData, kVisibleWidth,
                                      kVisibleHeight};
static_assert(kBitmap.Valid(), "packed data too small for its dimensions");

}  // namespace sd_card_bitmap
