#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

// Generated by tools/png_conv.py from usb-src.png
namespace usb_bitmap {

inline constexpr std::size_t kVisibleWidth = 16;
inline constexpr std::size_t kVisibleHeight = 9;
inline constexpr std::size_t kCanvasWidth = 128;
inline constexpr std::size_t kCanvasHeight = 64;
inline constexpr std::size_t kOffsetX = 28;
inline constexpr std::size_t kOffsetY = 24;
inline constexpr std::size_t kVisiblePageCount = 2;
inline constexpr std::array<std::uint8_t, 32> kBitmapData = {
    0x38, 0x38, 0x18, 0x1C, 0x16, 0x32, 0x52, 0x92, 0x93, 0x93, 0x90, 0x90,
    0x38, 0x38, 0x10, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00,
};

}  // namespace usb_bitmap
