#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

#include "packed_bitmap.hpp"

// Generated by tools/png_conv.py from wifi.png
namespace wifi_bitmap {

inline constexpr std::size_t kVisibleWidth = 10;
inline constexpr std::size_t kVisibleHeight = 10;
inline constexpr std::size_t kCanvasWidth = 10;
inline constexpr std::size_t kCanvasHeight = 16;
inline constexpr std::size_t kOffsetX = 0;
inline constexpr std::size_t kOffsetY = 0;
inline constexpr std::size_t kVisiblePageCount = 2;
inline constexpr std::array<std::uint8_t, 20> kBitmapData = {
    0x0C, 0x16, 0x5A, 0x6B, 0xAD, 0xAD, 0x6B, 0x5A, 0x16, 0x0C,
    0x00, 0x00, 0x00, 0x00, 0x03, 0x03, 0x00, 0x00, 0x00, 0x00,
};

// Draw through this, not the parts: a call site that restates the dimensions
// can restate them wrongly, and nothing downstream would notice.
inline constexpr PackedBitmap kBitmap{kBitmapData, kVisibleWidth,
                                      kVisibleHeight};
static_assert(kBitmap.Valid(), "packed data too small for its dimensions");

}  // namespace wifi_bitmap
