#!/usr/bin/env python3

# /// script
# dependencies = [
#     "jinja2",
#     "kconfiglib",
# ]
# ///

from __future__ import annotations

import argparse
import pathlib

import kconfiglib
try:
    from jinja2 import Environment, FileSystemLoader, StrictUndefined
except ImportError as exc:
    raise SystemExit(
        "jinja2 is required for generate_stm32_config.py. Install it in the "
        "active Python environment."
    ) from exc


AUTOGEN_WARNING = (
    "// This file is autogenerated. Do not modify manually.\n" "// Source: {source}\n"
)
TEMPLATE_DIR = pathlib.Path(__file__).with_name("templates")

ICM42688P_FIFO_BYTES = 2048
ICM42688P_PACKET3_BYTES = 16
FCLINK_TELEMETRY_RATE_MIN = 1
FCLINK_TELEMETRY_RATE_MAX = 255

SPI_PRESCALER_CHOICES = {
    "STM32_IMU_SPI_PRESCALER_DIV2": "SpiPrescaler::kDiv2",
    "STM32_IMU_SPI_PRESCALER_DIV4": "SpiPrescaler::kDiv4",
    "STM32_IMU_SPI_PRESCALER_DIV8": "SpiPrescaler::kDiv8",
    "STM32_IMU_SPI_PRESCALER_DIV16": "SpiPrescaler::kDiv16",
    "STM32_IMU_SPI_PRESCALER_DIV32": "SpiPrescaler::kDiv32",
    "STM32_IMU_SPI_PRESCALER_DIV64": "SpiPrescaler::kDiv64",
    "STM32_IMU_SPI_PRESCALER_DIV128": "SpiPrescaler::kDiv128",
    "STM32_IMU_SPI_PRESCALER_DIV256": "SpiPrescaler::kDiv256",
}

ICM20948_SPI_PRESCALER_CHOICES = {
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV2": "SpiPrescaler::kDiv2",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV4": "SpiPrescaler::kDiv4",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV8": "SpiPrescaler::kDiv8",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV16": "SpiPrescaler::kDiv16",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV32": "SpiPrescaler::kDiv32",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV64": "SpiPrescaler::kDiv64",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV128": "SpiPrescaler::kDiv128",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV256": "SpiPrescaler::kDiv256",
}

M10_BAUD_RATE_CHOICES = {
    "STM32_GPS_M10_BAUD_9600": "M10::BaudRate::k9600",
    "STM32_GPS_M10_BAUD_19200": "M10::BaudRate::k19200",
    "STM32_GPS_M10_BAUD_38400": "M10::BaudRate::k38400",
    "STM32_GPS_M10_BAUD_57600": "M10::BaudRate::k57600",
    "STM32_GPS_M10_BAUD_115200": "M10::BaudRate::k115200",
    "STM32_GPS_M10_BAUD_230400": "M10::BaudRate::k230400",
    "STM32_GPS_M10_BAUD_460800": "M10::BaudRate::k460800",
    "STM32_GPS_M10_BAUD_921600": "M10::BaudRate::k921600",
}

M10_UART_BAUD_RATE_CHOICES = {
    "STM32_GPS_M10_BAUD_9600": "9600",
    "STM32_GPS_M10_BAUD_19200": "19200",
    "STM32_GPS_M10_BAUD_38400": "38400",
    "STM32_GPS_M10_BAUD_57600": "57600",
    "STM32_GPS_M10_BAUD_115200": "115200",
    "STM32_GPS_M10_BAUD_230400": "230400",
    "STM32_GPS_M10_BAUD_460800": "460800",
    "STM32_GPS_M10_BAUD_921600": "921600",
}

FCLINK_UART_BAUD_RATE_CHOICES = {
    "ESP32_FCLINK_UART_BAUD_9600": "9600",
    "ESP32_FCLINK_UART_BAUD_19200": "19200",
    "ESP32_FCLINK_UART_BAUD_38400": "38400",
    "ESP32_FCLINK_UART_BAUD_57600": "57600",
    "ESP32_FCLINK_UART_BAUD_115200": "115200",
    "ESP32_FCLINK_UART_BAUD_230400": "230400",
    "ESP32_FCLINK_UART_BAUD_460800": "460800",
    "ESP32_FCLINK_UART_BAUD_921600": "921600",
    "ESP32_FCLINK_UART_BAUD_1000000": "1000000",
    "ESP32_FCLINK_UART_BAUD_2000000": "2000000",
    "ESP32_FCLINK_UART_BAUD_5000000": "5000000",
}

FCLINK_UART_WORD_LENGTH_CHOICES = {
    "STM32_FCLINK_UART_WORD_LENGTH_8BITS": "UartWordLength::k8Bits",
    "STM32_FCLINK_UART_WORD_LENGTH_9BITS": "UartWordLength::k9Bits",
}

FCLINK_UART_STOP_BITS_CHOICES = {
    "STM32_FCLINK_UART_STOP_BITS_1": "UartStopBits::k1",
    "STM32_FCLINK_UART_STOP_BITS_2": "UartStopBits::k2",
}

FCLINK_UART_PARITY_CHOICES = {
    "STM32_FCLINK_UART_PARITY_NONE": "UartParity::kNone",
    "STM32_FCLINK_UART_PARITY_EVEN": "UartParity::kEven",
    "STM32_FCLINK_UART_PARITY_ODD": "UartParity::kOdd",
}

FCLINK_UART_MODE_CHOICES = {
    "STM32_FCLINK_UART_MODE_RX": "UartMode::kRx",
    "STM32_FCLINK_UART_MODE_TX": "UartMode::kTx",
    "STM32_FCLINK_UART_MODE_TX_RX": "UartMode::kTxRx",
}

FCLINK_UART_HW_FLOW_CONTROL_CHOICES = {
    "STM32_FCLINK_UART_HW_FLOW_CONTROL_NONE": "UartHwFlowControl::kNone",
    "STM32_FCLINK_UART_HW_FLOW_CONTROL_RTS": "UartHwFlowControl::kRts",
    "STM32_FCLINK_UART_HW_FLOW_CONTROL_CTS": "UartHwFlowControl::kCts",
    "STM32_FCLINK_UART_HW_FLOW_CONTROL_RTS_CTS": "UartHwFlowControl::kRtsCts",
}

FCLINK_UART_OVERSAMPLING_CHOICES = {
    "STM32_FCLINK_UART_OVERSAMPLING_16": "UartOverSampling::k16",
    "STM32_FCLINK_UART_OVERSAMPLING_8": "UartOverSampling::k8",
}

M10_DYNAMIC_MODEL_CHOICES = {
    "STM32_GPS_M10_DYN_MODEL_PORTABLE": "M10::DynamicModel::kPortable",
    "STM32_GPS_M10_DYN_MODEL_STATIONARY": "M10::DynamicModel::kStationary",
    "STM32_GPS_M10_DYN_MODEL_PEDESTRIAN": "M10::DynamicModel::kPedestrian",
    "STM32_GPS_M10_DYN_MODEL_AUTOMOTIVE": "M10::DynamicModel::kAutomotive",
    "STM32_GPS_M10_DYN_MODEL_SEA": "M10::DynamicModel::kSea",
    "STM32_GPS_M10_DYN_MODEL_AIRBORNE_1G": "M10::DynamicModel::kAirborne1g",
    "STM32_GPS_M10_DYN_MODEL_AIRBORNE_2G": "M10::DynamicModel::kAirborne2g",
    "STM32_GPS_M10_DYN_MODEL_AIRBORNE_4G": "M10::DynamicModel::kAirborne4g",
    "STM32_GPS_M10_DYN_MODEL_WRIST": "M10::DynamicModel::kWrist",
    "STM32_GPS_M10_DYN_MODEL_BIKE": "M10::DynamicModel::kBike",
}

M10_TIMEGRID_CHOICES = {
    "STM32_GPS_M10_TP1_TIMEGRID_UTC": "M10::TimeGrid::kUtc",
    "STM32_GPS_M10_TP1_TIMEGRID_GPS": "M10::TimeGrid::kGps",
    "STM32_GPS_M10_TP1_TIMEGRID_GLONASS": "M10::TimeGrid::kGlonass",
    "STM32_GPS_M10_TP1_TIMEGRID_BEIDOU": "M10::TimeGrid::kBeiDou",
    "STM32_GPS_M10_TP1_TIMEGRID_GALILEO": "M10::TimeGrid::kGalileo",
}

M10_UART_WORD_LENGTH_CHOICES = {
    "STM32_GPS_M10_UART_WORD_LENGTH_8BITS": "UartWordLength::k8Bits",
    "STM32_GPS_M10_UART_WORD_LENGTH_9BITS": "UartWordLength::k9Bits",
}

M10_UART_STOP_BITS_CHOICES = {
    "STM32_GPS_M10_UART_STOP_BITS_1": "UartStopBits::k1",
    "STM32_GPS_M10_UART_STOP_BITS_2": "UartStopBits::k2",
}

M10_UART_PARITY_CHOICES = {
    "STM32_GPS_M10_UART_PARITY_NONE": "UartParity::kNone",
    "STM32_GPS_M10_UART_PARITY_EVEN": "UartParity::kEven",
    "STM32_GPS_M10_UART_PARITY_ODD": "UartParity::kOdd",
}

M10_UART_MODE_CHOICES = {
    "STM32_GPS_M10_UART_MODE_RX": "UartMode::kRx",
    "STM32_GPS_M10_UART_MODE_TX": "UartMode::kTx",
    "STM32_GPS_M10_UART_MODE_TX_RX": "UartMode::kTxRx",
}

M10_UART_HW_FLOW_CONTROL_CHOICES = {
    "STM32_GPS_M10_UART_HW_FLOW_CONTROL_NONE": "UartHwFlowControl::kNone",
    "STM32_GPS_M10_UART_HW_FLOW_CONTROL_RTS": "UartHwFlowControl::kRts",
    "STM32_GPS_M10_UART_HW_FLOW_CONTROL_CTS": "UartHwFlowControl::kCts",
    "STM32_GPS_M10_UART_HW_FLOW_CONTROL_RTS_CTS": "UartHwFlowControl::kRtsCts",
}

M10_UART_OVERSAMPLING_CHOICES = {
    "STM32_GPS_M10_UART_OVERSAMPLING_16": "UartOverSampling::k16",
    "STM32_GPS_M10_UART_OVERSAMPLING_8": "UartOverSampling::k8",
}

M10_CFG_UART_STOP_BITS_CHOICES = {
    "STM32_GPS_M10_UART_STOP_BITS_1": "M10::UartStopBits::k1",
    "STM32_GPS_M10_UART_STOP_BITS_2": "M10::UartStopBits::k2",
}

M10_CFG_UART_PARITY_CHOICES = {
    "STM32_GPS_M10_UART_PARITY_NONE": "M10::UartParity::kNone",
    "STM32_GPS_M10_UART_PARITY_EVEN": "M10::UartParity::kEven",
    "STM32_GPS_M10_UART_PARITY_ODD": "M10::UartParity::kOdd",
}

ODR_CHOICES = {
    "STM32_IMU_GYRO_ODR_32KHZ": "Icm42688pReg::Odr::k32kHz",
    "STM32_IMU_GYRO_ODR_16KHZ": "Icm42688pReg::Odr::k16kHz",
    "STM32_IMU_GYRO_ODR_8KHZ": "Icm42688pReg::Odr::k8kHz",
    "STM32_IMU_GYRO_ODR_4KHZ": "Icm42688pReg::Odr::k4kHz",
    "STM32_IMU_GYRO_ODR_2KHZ": "Icm42688pReg::Odr::k2kHz",
    "STM32_IMU_GYRO_ODR_1KHZ": "Icm42688pReg::Odr::k1kHz",
    "STM32_IMU_GYRO_ODR_500HZ": "Icm42688pReg::Odr::k500Hz",
    "STM32_IMU_GYRO_ODR_200HZ": "Icm42688pReg::Odr::k200Hz",
    "STM32_IMU_GYRO_ODR_100HZ": "Icm42688pReg::Odr::k100Hz",
    "STM32_IMU_GYRO_ODR_50HZ": "Icm42688pReg::Odr::k50Hz",
    "STM32_IMU_GYRO_ODR_25HZ": "Icm42688pReg::Odr::k25Hz",
    "STM32_IMU_GYRO_ODR_12_5HZ": "Icm42688pReg::Odr::k12_5Hz",
}

ACCEL_ODR_CHOICES = {
    key.replace("GYRO", "ACCEL"): value for key, value in ODR_CHOICES.items()
}

GYRO_FS_CHOICES = {
    "STM32_IMU_GYRO_FS_2000DPS": "Icm42688pReg::GyroFs::k2000dps",
    "STM32_IMU_GYRO_FS_1000DPS": "Icm42688pReg::GyroFs::k1000dps",
    "STM32_IMU_GYRO_FS_500DPS": "Icm42688pReg::GyroFs::k500dps",
    "STM32_IMU_GYRO_FS_250DPS": "Icm42688pReg::GyroFs::k250dps",
    "STM32_IMU_GYRO_FS_125DPS": "Icm42688pReg::GyroFs::k125dps",
    "STM32_IMU_GYRO_FS_62_5DPS": "Icm42688pReg::GyroFs::k62_5dps",
    "STM32_IMU_GYRO_FS_31_25DPS": "Icm42688pReg::GyroFs::k31_25dps",
    "STM32_IMU_GYRO_FS_15_625DPS": "Icm42688pReg::GyroFs::k15_625dps",
}

ACCEL_FS_CHOICES = {
    "STM32_IMU_ACCEL_FS_16G": "Icm42688pReg::AccelFs::k16g",
    "STM32_IMU_ACCEL_FS_8G": "Icm42688pReg::AccelFs::k8g",
    "STM32_IMU_ACCEL_FS_4G": "Icm42688pReg::AccelFs::k4g",
    "STM32_IMU_ACCEL_FS_2G": "Icm42688pReg::AccelFs::k2g",
}


def _sym(kconf: kconfiglib.Kconfig, name: str) -> kconfiglib.Symbol:
    sym = kconf.syms.get(name)
    if sym is None:
        raise ValueError(f"missing Kconfig symbol '{name}'")
    return sym


def _sym_int(kconf: kconfiglib.Kconfig, name: str) -> int:
    return int(_sym(kconf, name).str_value)


def _sym_bool(kconf: kconfiglib.Kconfig, name: str) -> bool:
    return _sym(kconf, name).tri_value == 2


def _choice_value(kconf: kconfiglib.Kconfig, mapping: dict[str, str]) -> str:
    for symbol_name, value in mapping.items():
        if _sym_bool(kconf, symbol_name):
            return value
    raise ValueError(f"no selected symbol in choice {tuple(mapping.keys())}")


def _m10_uart_data_bits_value(kconf: kconfiglib.Kconfig) -> str:
    word_length_9 = _sym_bool(kconf, "STM32_GPS_M10_UART_WORD_LENGTH_9BITS")
    parity_none = _sym_bool(kconf, "STM32_GPS_M10_UART_PARITY_NONE")

    if word_length_9 and parity_none:
        raise ValueError(
            "CONFIG_STM32_GPS_M10_UART_WORD_LENGTH_9BITS requires parity on the "
            "M10 link; choose 8 bits or enable parity"
        )

    if word_length_9:
        return "M10::UartDataBits::k8"
    if parity_none:
        return "M10::UartDataBits::k8"
    return "M10::UartDataBits::k7"


def _imu_fifo_capacity_records() -> int:
    return ICM42688P_FIFO_BYTES // ICM42688P_PACKET3_BYTES


def _validate(kconf: kconfiglib.Kconfig) -> None:
    telemetry_rate_hz = _sym_int(kconf, "STM32_FCLINK_TELEMETRY_RATE_HZ")
    if not FCLINK_TELEMETRY_RATE_MIN <= telemetry_rate_hz <= FCLINK_TELEMETRY_RATE_MAX:
        raise ValueError(
            "CONFIG_STM32_FCLINK_TELEMETRY_RATE_HZ must be in the range "
            f"{FCLINK_TELEMETRY_RATE_MIN}..{FCLINK_TELEMETRY_RATE_MAX}"
        )

    watermark_records = _sym_int(kconf, "STM32_IMU_FIFO_WATERMARK_RECORDS")
    hardware_max_records = _imu_fifo_capacity_records()
    if watermark_records <= 0:
        raise ValueError("CONFIG_STM32_IMU_FIFO_WATERMARK_RECORDS must be > 0")
    if watermark_records > hardware_max_records:
        raise ValueError(
            "CONFIG_STM32_IMU_FIFO_WATERMARK_RECORDS exceeds ICM42688P FIFO capacity "
            f"({watermark_records} > {hardware_max_records})"
        )


def _cpp_bool(value: bool) -> str:
    return "true" if value else "false"


def _template_env() -> Environment:
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    env.filters["cpp_bool"] = _cpp_bool
    return env


def _render_template(template_name: str, context: dict[str, object]) -> str:
    return _template_env().get_template(template_name).render(**context)


def _enabled_rc_channels(kconf: kconfiglib.Kconfig) -> list[bool]:
    return [
        _sym_bool(kconf, f"STM32_RC_CHANNEL_{channel_index + 1}_ENABLED")
        for channel_index in range(16)
    ]


def _limits_context(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> dict[str, object]:
    enabled_rc_channels = _enabled_rc_channels(kconf)
    enabled_rc_indices = [
        channel_index
        for channel_index, enabled in enumerate(enabled_rc_channels)
        if enabled
    ]
    return {
        "autogen_warning": AUTOGEN_WARNING.format(source=source.name),
        "max_watermark_records": _sym_int(kconf, "STM32_IMU_FIFO_WATERMARK_RECORDS"),
        "rc_enabled_indices": enabled_rc_indices,
    }


def _runtime_context(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> dict[str, object]:
    return {
        "autogen_warning": AUTOGEN_WARNING.format(source=source.name),
        "fclink": {
            "telemetry_rate_hz": _sym_int(kconf, "STM32_FCLINK_TELEMETRY_RATE_HZ"),
            "uart": {
                "baud_rate": _choice_value(kconf, FCLINK_UART_BAUD_RATE_CHOICES),
                "word_length": _choice_value(kconf, FCLINK_UART_WORD_LENGTH_CHOICES),
                "stop_bits": _choice_value(kconf, FCLINK_UART_STOP_BITS_CHOICES),
                "parity": _choice_value(kconf, FCLINK_UART_PARITY_CHOICES),
                "mode": _choice_value(kconf, FCLINK_UART_MODE_CHOICES),
                "hw_flow_control": _choice_value(
                    kconf, FCLINK_UART_HW_FLOW_CONTROL_CHOICES
                ),
                "over_sampling": _choice_value(
                    kconf, FCLINK_UART_OVERSAMPLING_CHOICES
                ),
            },
        },
        "m10": {
            "uart": {
                "baud_rate": _choice_value(kconf, M10_UART_BAUD_RATE_CHOICES),
                "word_length": _choice_value(kconf, M10_UART_WORD_LENGTH_CHOICES),
                "stop_bits": _choice_value(kconf, M10_UART_STOP_BITS_CHOICES),
                "parity": _choice_value(kconf, M10_UART_PARITY_CHOICES),
                "mode": _choice_value(kconf, M10_UART_MODE_CHOICES),
                "hw_flow_control": _choice_value(
                    kconf, M10_UART_HW_FLOW_CONTROL_CHOICES
                ),
                "over_sampling": _choice_value(
                    kconf, M10_UART_OVERSAMPLING_CHOICES
                ),
            },
            "config": {
                "baud_rate": _choice_value(kconf, M10_BAUD_RATE_CHOICES),
                "uart1": {
                    "enabled": _sym_bool(kconf, "STM32_GPS_M10_UART_ENABLED"),
                    "stop_bits": _choice_value(kconf, M10_CFG_UART_STOP_BITS_CHOICES),
                    "data_bits": _m10_uart_data_bits_value(kconf),
                    "parity": _choice_value(kconf, M10_CFG_UART_PARITY_CHOICES),
                },
                "protocols": {
                    "outprot_ubx": _sym_bool(kconf, "STM32_GPS_M10_PROTOCOL_UBX"),
                    "outprot_nmea": _sym_bool(kconf, "STM32_GPS_M10_PROTOCOL_NMEA"),
                },
                "messages": {
                    "nav_pvt": _sym_bool(kconf, "STM32_GPS_M10_MSG_NAV_PVT"),
                    "nav_dop": _sym_bool(kconf, "STM32_GPS_M10_MSG_NAV_DOP"),
                    "nav_cov": _sym_bool(kconf, "STM32_GPS_M10_MSG_NAV_COV"),
                    "nav_eoe": _sym_bool(kconf, "STM32_GPS_M10_MSG_NAV_EOE"),
                },
                "nav": {
                    "rate_meas_ms": _sym_int(kconf, "STM32_GPS_M10_RATE_MEAS_MS"),
                    "dyn_model": _choice_value(kconf, M10_DYNAMIC_MODEL_CHOICES),
                },
                "gnss": {
                    "gps_enable": _sym_bool(kconf, "STM32_GPS_M10_GNSS_GPS"),
                    "glo_enable": _sym_bool(kconf, "STM32_GPS_M10_GNSS_GLO"),
                    "gal_enable": _sym_bool(kconf, "STM32_GPS_M10_GNSS_GAL"),
                    "bds_enable": _sym_bool(kconf, "STM32_GPS_M10_GNSS_BDS"),
                    "sbas_enable": _sym_bool(kconf, "STM32_GPS_M10_GNSS_SBAS"),
                    "itfm_enable": _sym_bool(kconf, "STM32_GPS_M10_GNSS_ITFM"),
                },
                "tp1": {
                    "ena": _sym_bool(kconf, "STM32_GPS_M10_TP1_ENA"),
                    "period": _sym_int(kconf, "STM32_GPS_M10_TP1_PERIOD"),
                    "len": _sym_int(kconf, "STM32_GPS_M10_TP1_LEN"),
                    "timegrid": _choice_value(kconf, M10_TIMEGRID_CHOICES),
                    "sync_gnss": _sym_bool(kconf, "STM32_GPS_M10_TP1_SYNC_GNSS"),
                    "align_to_tow": _sym_bool(
                        kconf, "STM32_GPS_M10_TP1_ALIGN_TO_TOW"
                    ),
                    "pol_rising": _sym_bool(kconf, "STM32_GPS_M10_TP1_POL_RISING"),
                },
                "ack_timeout_us": _sym_int(kconf, "STM32_GPS_M10_ACK_TIMEOUT_US"),
            },
        },
        "icm42688p": {
            "spi_prescaler": _choice_value(kconf, SPI_PRESCALER_CHOICES),
            "rates": {
                "gyro": _choice_value(kconf, ODR_CHOICES),
                "accel": _choice_value(kconf, ACCEL_ODR_CHOICES),
            },
            "fs": {
                "gyro": _choice_value(kconf, GYRO_FS_CHOICES),
                "accel": _choice_value(kconf, ACCEL_FS_CHOICES),
            },
            "ui_filter": {
                "gyro_bw": _sym_int(kconf, "STM32_IMU_UI_FILTER_GYRO_BW"),
                "accel_bw": _sym_int(kconf, "STM32_IMU_UI_FILTER_ACCEL_BW"),
                "gyro_cfg1": _sym_int(kconf, "STM32_IMU_UI_FILTER_GYRO_CFG1"),
                "accel_cfg1": _sym_int(kconf, "STM32_IMU_UI_FILTER_ACCEL_CFG1"),
            },
            "notch": {
                "freq_hz": f'{float(_sym_int(kconf, "STM32_IMU_NOTCH_FREQ_HZ")):.6f}f',
                "bw_idx": _sym_int(kconf, "STM32_IMU_NOTCH_BW_IDX"),
                "enabled": _sym_bool(kconf, "STM32_IMU_NOTCH_ENABLED"),
            },
            "gyro_aaf": {
                "dis": _sym_bool(kconf, "STM32_IMU_GYRO_AAF_DISABLE"),
                "delt": _sym_int(kconf, "STM32_IMU_GYRO_AAF_DELT"),
                "delt_sqr": _sym_int(kconf, "STM32_IMU_GYRO_AAF_DELT_SQR"),
                "bitshift": _sym_int(kconf, "STM32_IMU_GYRO_AAF_BITSHIFT"),
            },
            "accel_aaf": {
                "dis": _sym_bool(kconf, "STM32_IMU_ACCEL_AAF_DISABLE"),
                "delt": _sym_int(kconf, "STM32_IMU_ACCEL_AAF_DELT"),
                "delt_sqr": _sym_int(kconf, "STM32_IMU_ACCEL_AAF_DELT_SQR"),
                "bitshift": _sym_int(kconf, "STM32_IMU_ACCEL_AAF_BITSHIFT"),
            },
            "fifo": {
                "watermark_records": _sym_int(
                    kconf, "STM32_IMU_FIFO_WATERMARK_RECORDS"
                ),
                "hold_last": _sym_bool(kconf, "STM32_IMU_FIFO_HOLD_LAST"),
            },
            "calibration": {
                "gyro_duration_s": _sym_int(kconf, "STM32_IMU_GYRO_CAL_DURATION_S"),
                "gyro_timeout_s": _sym_int(kconf, "STM32_IMU_GYRO_CAL_TIMEOUT_S"),
                "gyro_still_threshold_raw": _sym_int(
                    kconf, "STM32_IMU_GYRO_CAL_STILL_THRESHOLD_RAW"
                ),
            },
            "recovery": {
                "overrun_threshold": _sym_int(
                    kconf, "STM32_IMU_RECOVERY_OVERRUN_THRESHOLD"
                ),
                "overrun_window_s": _sym_int(
                    kconf, "STM32_IMU_RECOVERY_OVERRUN_WINDOW_S"
                ),
                "fault_led_period_ms": _sym_int(
                    kconf, "STM32_IMU_RECOVERY_FAULT_LED_PERIOD_MS"
                ),
            },
        },
        "icm20948": {
            "dma_buf_size": _sym_int(kconf, "STM32_IMU_ICM20948_DMA_BUF_SIZE"),
            "fifo_size": _sym_int(kconf, "STM32_IMU_ICM20948_FIFO_SIZE"),
            "accel": {
                "range": _sym(kconf, "STM32_IMU_ICM20948_ACCEL_RANGE").str_value,
                "dlpf_config": _sym(
                    kconf, "STM32_IMU_ICM20948_ACCEL_DLPF_CONFIG"
                ).str_value,
                "sample_rate_div": _sym_int(
                    kconf, "STM32_IMU_ICM20948_ACCEL_SAMPLE_RATE_DIV"
                ),
            },
            "gyro": {
                "range": _sym(kconf, "STM32_IMU_ICM20948_GYRO_RANGE").str_value,
                "dlpf_config": _sym(
                    kconf, "STM32_IMU_ICM20948_GYRO_DLPF_CONFIG"
                ).str_value,
                "sample_rate_div": _sym_int(
                    kconf, "STM32_IMU_ICM20948_GYRO_SAMPLE_RATE_DIV"
                ),
            },
            "mag_rate": _sym(kconf, "STM32_IMU_ICM20948_MAG_RATE").str_value,
            "spi_prescaler": _choice_value(kconf, ICM20948_SPI_PRESCALER_CHOICES),
        },
        "button": {
            "active_low": _sym_bool(kconf, "STM32_BUTTON_ACTIVE_LOW"),
            "debounce_ms": _sym_int(kconf, "STM32_BUTTON_DEBOUNCE_MS"),
            "long_press_ms": _sym_int(kconf, "STM32_BUTTON_LONG_PRESS_MS"),
        },
        "rc_receiver": {
            "enabled_channels": _enabled_rc_channels(kconf),
        },
    }


def _emit_limits_header(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> str:
    return _render_template("stm32_limits.hpp.j2", _limits_context(source, kconf))


def _emit_runtime_header(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> str:
    return _render_template("stm32_config.hpp.j2", _runtime_context(source, kconf))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kconfig", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--runtime-out", required=True)
    parser.add_argument("--limits-out", required=True)
    args = parser.parse_args()

    kconfig_path = pathlib.Path(args.kconfig).resolve()
    config_path = pathlib.Path(args.config).resolve()
    runtime_out = pathlib.Path(args.runtime_out).resolve()
    limits_out = pathlib.Path(args.limits_out).resolve()

    kconf = kconfiglib.Kconfig(str(kconfig_path))
    if config_path.exists():
        kconf.load_config(str(config_path))

    _validate(kconf)

    runtime_out.parent.mkdir(parents=True, exist_ok=True)
    limits_out.parent.mkdir(parents=True, exist_ok=True)

    limits_out.write_text(_emit_limits_header(config_path, kconf), encoding="ascii")
    runtime_out.write_text(_emit_runtime_header(config_path, kconf), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
