#!/usr/bin/env python3

from __future__ import annotations

import argparse
import pathlib
import textwrap

import kconfiglib


AUTOGEN_WARNING = (
    "// This file is autogenerated. Do not modify manually.\n" "// Source: {source}\n"
)

ICM42688P_FIFO_BYTES = 2048
ICM42688P_PACKET3_BYTES = 16

SPI_PRESCALER_CHOICES = {
    "STM32_IMU_SPI_PRESCALER_DIV2": "SpiPrescaler::kDiv2",
    "STM32_IMU_SPI_PRESCALER_DIV4": "SpiPrescaler::kDiv4",
    "STM32_IMU_SPI_PRESCALER_DIV8": "SpiPrescaler::kDiv8",
    "STM32_IMU_SPI_PRESCALER_DIV16": "SpiPrescaler::kDiv16",
    "STM32_IMU_SPI_PRESCALER_DIV32": "SpiPrescaler::kDiv32",
    "STM32_IMU_SPI_PRESCALER_DIV64": "SpiPrescaler::kDiv64",
    "STM32_IMU_SPI_PRESCALER_DIV128": "SpiPrescaler::kDiv128",
    "STM32_IMU_SPI_PRESCALER_DIV256": "SpiPrescaler::kDiv256",
}

ODR_CHOICES = {
    "STM32_IMU_GYRO_ODR_32KHZ": "Icm42688pReg::Odr::k32kHz",
    "STM32_IMU_GYRO_ODR_16KHZ": "Icm42688pReg::Odr::k16kHz",
    "STM32_IMU_GYRO_ODR_8KHZ": "Icm42688pReg::Odr::k8kHz",
    "STM32_IMU_GYRO_ODR_4KHZ": "Icm42688pReg::Odr::k4kHz",
    "STM32_IMU_GYRO_ODR_2KHZ": "Icm42688pReg::Odr::k2kHz",
    "STM32_IMU_GYRO_ODR_1KHZ": "Icm42688pReg::Odr::k1kHz",
    "STM32_IMU_GYRO_ODR_500HZ": "Icm42688pReg::Odr::k500Hz",
    "STM32_IMU_GYRO_ODR_200HZ": "Icm42688pReg::Odr::k200Hz",
    "STM32_IMU_GYRO_ODR_100HZ": "Icm42688pReg::Odr::k100Hz",
    "STM32_IMU_GYRO_ODR_50HZ": "Icm42688pReg::Odr::k50Hz",
    "STM32_IMU_GYRO_ODR_25HZ": "Icm42688pReg::Odr::k25Hz",
    "STM32_IMU_GYRO_ODR_12_5HZ": "Icm42688pReg::Odr::k12_5Hz",
}

ACCEL_ODR_CHOICES = {
    key.replace("GYRO", "ACCEL"): value for key, value in ODR_CHOICES.items()
}

GYRO_FS_CHOICES = {
    "STM32_IMU_GYRO_FS_2000DPS": "Icm42688pReg::GyroFs::k2000dps",
    "STM32_IMU_GYRO_FS_1000DPS": "Icm42688pReg::GyroFs::k1000dps",
    "STM32_IMU_GYRO_FS_500DPS": "Icm42688pReg::GyroFs::k500dps",
    "STM32_IMU_GYRO_FS_250DPS": "Icm42688pReg::GyroFs::k250dps",
    "STM32_IMU_GYRO_FS_125DPS": "Icm42688pReg::GyroFs::k125dps",
    "STM32_IMU_GYRO_FS_62_5DPS": "Icm42688pReg::GyroFs::k62_5dps",
    "STM32_IMU_GYRO_FS_31_25DPS": "Icm42688pReg::GyroFs::k31_25dps",
    "STM32_IMU_GYRO_FS_15_625DPS": "Icm42688pReg::GyroFs::k15_625dps",
}

ACCEL_FS_CHOICES = {
    "STM32_IMU_ACCEL_FS_16G": "Icm42688pReg::AccelFs::k16g",
    "STM32_IMU_ACCEL_FS_8G": "Icm42688pReg::AccelFs::k8g",
    "STM32_IMU_ACCEL_FS_4G": "Icm42688pReg::AccelFs::k4g",
    "STM32_IMU_ACCEL_FS_2G": "Icm42688pReg::AccelFs::k2g",
}


def _sym(kconf: kconfiglib.Kconfig, name: str) -> kconfiglib.Symbol:
    sym = kconf.syms.get(name)
    if sym is None:
        raise ValueError(f"missing Kconfig symbol '{name}'")
    return sym


def _sym_int(kconf: kconfiglib.Kconfig, name: str) -> int:
    return int(_sym(kconf, name).str_value)


def _sym_bool(kconf: kconfiglib.Kconfig, name: str) -> bool:
    return _sym(kconf, name).tri_value == 2


def _choice_value(kconf: kconfiglib.Kconfig, mapping: dict[str, str]) -> str:
    for symbol_name, value in mapping.items():
        if _sym_bool(kconf, symbol_name):
            return value
    raise ValueError(f"no selected symbol in choice {tuple(mapping.keys())}")


def _imu_fifo_capacity_records() -> int:
    return ICM42688P_FIFO_BYTES // ICM42688P_PACKET3_BYTES


def _validate(kconf: kconfiglib.Kconfig) -> None:
    watermark_records = _sym_int(kconf, "STM32_IMU_FIFO_WATERMARK_RECORDS")
    hardware_max_records = _imu_fifo_capacity_records()
    if watermark_records <= 0:
        raise ValueError("CONFIG_STM32_IMU_FIFO_WATERMARK_RECORDS must be > 0")
    if watermark_records > hardware_max_records:
        raise ValueError(
            "CONFIG_STM32_IMU_FIFO_WATERMARK_RECORDS exceeds ICM42688P FIFO capacity "
            f"({watermark_records} > {hardware_max_records})"
        )


def _emit_limits_header(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> str:
    max_records = _sym_int(kconf, "STM32_IMU_FIFO_WATERMARK_RECORDS")
    return AUTOGEN_WARNING.format(source=source.name) + textwrap.dedent(
        f"""\
            #pragma once

            #include <cstdint>

            namespace stm32_limits {{

            inline constexpr uint16_t kIcm42688pMaxWatermarkRecords = {max_records};

            }} // namespace stm32_limits
            """
    )


def _emit_runtime_header(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> str:
    spi_prescaler = _choice_value(kconf, SPI_PRESCALER_CHOICES)
    gyro_odr = _choice_value(kconf, ODR_CHOICES)
    accel_odr = _choice_value(kconf, ACCEL_ODR_CHOICES)
    gyro_fs = _choice_value(kconf, GYRO_FS_CHOICES)
    accel_fs = _choice_value(kconf, ACCEL_FS_CHOICES)

    return AUTOGEN_WARNING.format(source=source.name) + textwrap.dedent(
        f"""\
            #pragma once

            #include "icm42688p.hpp"
            #include "spi.hpp"
            #include "stm32_limits.hpp"

            inline constexpr Icm42688p::Config kIcm42688pConfig = {{
                .spi_prescaler = static_cast<uint8_t>({spi_prescaler}),
                .rates = {{
                    .gyro = {gyro_odr},
                    .accel = {accel_odr},
                }},
                .fs = {{
                    .gyro = {gyro_fs},
                    .accel = {accel_fs},
                }},
                .ui_filter = {{
                    .gyro_bw = {_sym_int(kconf, "STM32_IMU_UI_FILTER_GYRO_BW")},
                    .accel_bw = {_sym_int(kconf, "STM32_IMU_UI_FILTER_ACCEL_BW")},
                    .gyro_cfg1 = {_sym_int(kconf, "STM32_IMU_UI_FILTER_GYRO_CFG1")},
                    .accel_cfg1 = {_sym_int(kconf, "STM32_IMU_UI_FILTER_ACCEL_CFG1")},
                }},
                .notch = {{
                    .freq_hz = {float(_sym_int(kconf, "STM32_IMU_NOTCH_FREQ_HZ")):.6f}f,
                    .bw_idx = {_sym_int(kconf, "STM32_IMU_NOTCH_BW_IDX")},
                    .enabled = {"true" if _sym_bool(kconf, "STM32_IMU_NOTCH_ENABLED") else "false"},
                }},
                .gyro_aaf = {{
                    .dis = {"true" if _sym_bool(kconf, "STM32_IMU_GYRO_AAF_DISABLE") else "false"},
                    .delt = {_sym_int(kconf, "STM32_IMU_GYRO_AAF_DELT")},
                    .delt_sqr = {_sym_int(kconf, "STM32_IMU_GYRO_AAF_DELT_SQR")},
                    .bitshift = {_sym_int(kconf, "STM32_IMU_GYRO_AAF_BITSHIFT")},
                }},
                .accel_aaf = {{
                    .dis = {"true" if _sym_bool(kconf, "STM32_IMU_ACCEL_AAF_DISABLE") else "false"},
                    .delt = {_sym_int(kconf, "STM32_IMU_ACCEL_AAF_DELT")},
                    .delt_sqr = {_sym_int(kconf, "STM32_IMU_ACCEL_AAF_DELT_SQR")},
                    .bitshift = {_sym_int(kconf, "STM32_IMU_ACCEL_AAF_BITSHIFT")},
                }},
                .fifo = {{
                    .watermark_records = {_sym_int(kconf, "STM32_IMU_FIFO_WATERMARK_RECORDS")},
                    .hold_last = {"true" if _sym_bool(kconf, "STM32_IMU_FIFO_HOLD_LAST") else "false"},
                }},
                .calibration = {{
                    .gyro_duration_s = {_sym_int(kconf, "STM32_IMU_GYRO_CAL_DURATION_S")},
                    .gyro_timeout_s = {_sym_int(kconf, "STM32_IMU_GYRO_CAL_TIMEOUT_S")},
                    .gyro_still_threshold_raw = {_sym_int(kconf, "STM32_IMU_GYRO_CAL_STILL_THRESHOLD_RAW")},
                }},
            }};
            """
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kconfig", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--runtime-out", required=True)
    parser.add_argument("--limits-out", required=True)
    args = parser.parse_args()

    kconfig_path = pathlib.Path(args.kconfig).resolve()
    config_path = pathlib.Path(args.config).resolve()
    runtime_out = pathlib.Path(args.runtime_out).resolve()
    limits_out = pathlib.Path(args.limits_out).resolve()

    kconf = kconfiglib.Kconfig(str(kconfig_path))
    if config_path.exists():
        kconf.load_config(str(config_path))

    _validate(kconf)

    runtime_out.parent.mkdir(parents=True, exist_ok=True)
    limits_out.parent.mkdir(parents=True, exist_ok=True)

    limits_out.write_text(_emit_limits_header(config_path, kconf), encoding="ascii")
    runtime_out.write_text(_emit_runtime_header(config_path, kconf), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
