#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import pathlib
import textwrap

import kconfiglib


AUTOGEN_WARNING = (
    "// This file is autogenerated. Do not modify manually.\n" "// Source: {source}\n"
)

ESP32C3_GPIO_MIN = 0
ESP32C3_GPIO_MAX = 21
FCLINK_TELEMETRY_RATE_MIN = 1
FCLINK_TELEMETRY_RATE_MAX = 255
FCLINK_HANDSHAKE_TIMEOUT_MIN_MS = 1
FCLINK_HANDSHAKE_TIMEOUT_MAX_MS = 10000
FCLINK_HANDSHAKE_RETRY_PERIOD_MIN_MS = 1
FCLINK_HANDSHAKE_RETRY_PERIOD_MAX_MS = 1000
FCLINK_RX_READ_CHUNK_MIN = 1
FCLINK_RX_READ_CHUNK_MAX = 256
FCLINK_RX_QUEUE_DEPTH_MIN = 1
FCLINK_RX_QUEUE_DEPTH_MAX = 32
UART_BUFFER_SIZE_MIN = 256
UART_BUFFER_SIZE_MAX = 16384
MAVLINK_SYSID_MIN = 1
MAVLINK_SYSID_MAX = 255
MAVLINK_COMPID_MIN = 0
MAVLINK_COMPID_MAX = 255
MAVLINK_HEARTBEAT_PERIOD_MIN_MS = 1
MAVLINK_HEARTBEAT_PERIOD_MAX_MS = 60000
MAVLINK_TELEMETRY_PERIOD_MIN_MS = 0
MAVLINK_TELEMETRY_PERIOD_MAX_MS = 60000
MAVLINK_RX_READ_CHUNK_MIN = 1
MAVLINK_RX_READ_CHUNK_MAX = 256
MAVLINK_HEARTBEAT_DEADLINE_MIN_MS = 1
MAVLINK_HEARTBEAT_DEADLINE_MAX_MS = 60000
MAVLINK_START_DELAY_MIN_MS = 0
MAVLINK_START_DELAY_MAX_MS = 10000
WIFI_AP_SSID_MIN_LEN = 1
WIFI_AP_SSID_MAX_LEN = 32
WIFI_AP_PASSWORD_MAX_LEN = 63
WIFI_AP_PASSWORD_MIN_LEN = 8
WIFI_AP_CHANNEL_MIN = 1
WIFI_AP_CHANNEL_MAX = 13
WIFI_AP_MAX_CONNECTIONS_MIN = 1
WIFI_AP_MAX_CONNECTIONS_MAX = 10
WIFI_AP_BEACON_INTERVAL_MIN_TU = 100
WIFI_AP_BEACON_INTERVAL_MAX_TU = 60000
PROGRAMMER_RESET_PULSE_MIN_MS = 1
PROGRAMMER_RESET_PULSE_MAX_MS = 1000
PROGRAMMER_BOOT_SETTLE_MIN_MS = 1
PROGRAMMER_BOOT_SETTLE_MAX_MS = 1000
PROGRAMMER_SYNC_TIMEOUT_MIN_MS = 1
PROGRAMMER_SYNC_TIMEOUT_MAX_MS = 5000
PROGRAMMER_SYNC_RETRIES_MIN = 1
PROGRAMMER_SYNC_RETRIES_MAX = 100

FCLINK_UART_BAUD_RATE_CHOICES = {
    "ESP32_FCLINK_UART_BAUD_9600": "9600",
    "ESP32_FCLINK_UART_BAUD_19200": "19200",
    "ESP32_FCLINK_UART_BAUD_38400": "38400",
    "ESP32_FCLINK_UART_BAUD_57600": "57600",
    "ESP32_FCLINK_UART_BAUD_115200": "115200",
    "ESP32_FCLINK_UART_BAUD_230400": "230400",
    "ESP32_FCLINK_UART_BAUD_460800": "460800",
    "ESP32_FCLINK_UART_BAUD_921600": "921600",
    "ESP32_FCLINK_UART_BAUD_1000000": "1000000",
    "ESP32_FCLINK_UART_BAUD_2000000": "2000000",
    "ESP32_FCLINK_UART_BAUD_5000000": "5000000",
}

FCLINK_UART_PARITY_CHOICES = {
    "ESP32_FCLINK_UART_PARITY_NONE": "UartParity::kNone",
    "ESP32_FCLINK_UART_PARITY_EVEN": "UartParity::kEven",
    "ESP32_FCLINK_UART_PARITY_ODD": "UartParity::kOdd",
}

RCRX_UART_BAUD_RATE_CHOICES = {
    "ESP32_RCRX_UART_BAUD_9600": "9600",
    "ESP32_RCRX_UART_BAUD_19200": "19200",
    "ESP32_RCRX_UART_BAUD_38400": "38400",
    "ESP32_RCRX_UART_BAUD_57600": "57600",
    "ESP32_RCRX_UART_BAUD_115200": "115200",
    "ESP32_RCRX_UART_BAUD_230400": "230400",
    "ESP32_RCRX_UART_BAUD_460800": "460800",
    "ESP32_RCRX_UART_BAUD_921600": "921600",
    "ESP32_RCRX_UART_BAUD_1000000": "1000000",
    "ESP32_RCRX_UART_BAUD_2000000": "2000000",
    "ESP32_RCRX_UART_BAUD_5000000": "5000000",
}

RCRX_UART_PARITY_CHOICES = {
    "ESP32_RCRX_UART_PARITY_NONE": "UartParity::kNone",
    "ESP32_RCRX_UART_PARITY_EVEN": "UartParity::kEven",
    "ESP32_RCRX_UART_PARITY_ODD": "UartParity::kOdd",
}

WIFI_POWER_SAVE_CHOICES = {
    "ESP32_WIFI_POWER_SAVE_NONE": "WIFI_PS_NONE",
    "ESP32_WIFI_POWER_SAVE_MIN_MODEM": "WIFI_PS_MIN_MODEM",
    "ESP32_WIFI_POWER_SAVE_MAX_MODEM": "WIFI_PS_MAX_MODEM",
}


def _sym(kconf: kconfiglib.Kconfig, name: str) -> kconfiglib.Symbol:
    sym = kconf.syms.get(name)
    if sym is None:
        raise ValueError(f"missing Kconfig symbol '{name}'")
    return sym


def _sym_int(kconf: kconfiglib.Kconfig, name: str) -> int:
    return int(_sym(kconf, name).str_value)


def _sym_bool(kconf: kconfiglib.Kconfig, name: str) -> bool:
    return _sym(kconf, name).str_value == "y"


def _choice_value(kconf: kconfiglib.Kconfig, mapping: dict[str, str]) -> str:
    for symbol_name, value in mapping.items():
        if _sym_bool(kconf, symbol_name):
            return value
    raise ValueError(f"no selected symbol in choice {tuple(mapping.keys())}")


def _sym_str(kconf: kconfiglib.Kconfig, name: str) -> str:
    return _sym(kconf, name).str_value


def _cpp_string_literal(value: str) -> str:
    return json.dumps(value)


def _validate_gpio_num(kconf: kconfiglib.Kconfig, name: str) -> None:
    gpio_num = _sym_int(kconf, name)
    if not ESP32C3_GPIO_MIN <= gpio_num <= ESP32C3_GPIO_MAX:
        raise ValueError(
            f"{name} must be an ESP32-C3 GPIO in the range "
            f"{ESP32C3_GPIO_MIN}..{ESP32C3_GPIO_MAX}"
        )


def _validate_int_range(
    kconf: kconfiglib.Kconfig, name: str, minimum: int, maximum: int
) -> None:
    value = _sym_int(kconf, name)
    if not minimum <= value <= maximum:
        raise ValueError(f"{name} must be in the range {minimum}..{maximum}")


def _validate_unique_gpio_assignments(
    kconf: kconfiglib.Kconfig, names: tuple[str, ...]
) -> None:
    assigned: dict[int, str] = {}
    duplicates: list[str] = []

    for name in names:
        gpio_num = _sym_int(kconf, name)
        previous = assigned.get(gpio_num)
        if previous is None:
            assigned[gpio_num] = name
            continue
        duplicates.append(f"GPIO{gpio_num}: {previous}, {name}")

    if duplicates:
        raise ValueError(
            "duplicate ESP32 pin assignments are not allowed: "
            + "; ".join(duplicates)
        )


def _validate(kconf: kconfiglib.Kconfig) -> None:
    gpio_symbols = (
        "ESP32_PINMAP_LED_GPIO_NUM",
        "ESP32_PINMAP_BUTTON_GPIO_NUM",
        "ESP32_PINMAP_BUZZER_GPIO_NUM",
        "ESP32_PINMAP_FCLINK_UART_TX_GPIO_NUM",
        "ESP32_PINMAP_FCLINK_UART_RX_GPIO_NUM",
        "ESP32_PINMAP_RCRX_UART_TX_GPIO_NUM",
        "ESP32_PINMAP_RCRX_UART_RX_GPIO_NUM",
        "ESP32_PINMAP_PROGRAMMER_BOOT0_GPIO_NUM",
        "ESP32_PINMAP_PROGRAMMER_NRST_GPIO_NUM",
    )
    for symbol in gpio_symbols:
        _validate_gpio_num(kconf, symbol)
    _validate_unique_gpio_assignments(kconf, gpio_symbols)
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_TELEMETRY_RATE_HZ",
        FCLINK_TELEMETRY_RATE_MIN,
        FCLINK_TELEMETRY_RATE_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_HANDSHAKE_TIMEOUT_MS",
        FCLINK_HANDSHAKE_TIMEOUT_MIN_MS,
        FCLINK_HANDSHAKE_TIMEOUT_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_HANDSHAKE_RETRY_PERIOD_MS",
        FCLINK_HANDSHAKE_RETRY_PERIOD_MIN_MS,
        FCLINK_HANDSHAKE_RETRY_PERIOD_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_RX_READ_CHUNK_SIZE",
        FCLINK_RX_READ_CHUNK_MIN,
        FCLINK_RX_READ_CHUNK_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_RX_QUEUE_DEPTH",
        FCLINK_RX_QUEUE_DEPTH_MIN,
        FCLINK_RX_QUEUE_DEPTH_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_UART_RX_BUFFER_SIZE",
        UART_BUFFER_SIZE_MIN,
        UART_BUFFER_SIZE_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_UART_TX_BUFFER_SIZE",
        UART_BUFFER_SIZE_MIN,
        UART_BUFFER_SIZE_MAX,
    )
    _validate_int_range(
        kconf, "ESP32_MAVLINK_SYSID", MAVLINK_SYSID_MIN, MAVLINK_SYSID_MAX
    )
    _validate_int_range(
        kconf, "ESP32_MAVLINK_COMPID", MAVLINK_COMPID_MIN, MAVLINK_COMPID_MAX
    )
    _validate_int_range(
        kconf,
        "ESP32_MAVLINK_HEARTBEAT_PERIOD_MS",
        MAVLINK_HEARTBEAT_PERIOD_MIN_MS,
        MAVLINK_HEARTBEAT_PERIOD_MAX_MS,
    )
    for symbol in (
        "ESP32_MAVLINK_GPS_PERIOD_MS",
        "ESP32_MAVLINK_ATTITUDE_PERIOD_MS",
        "ESP32_MAVLINK_GLOBAL_POSITION_PERIOD_MS",
        "ESP32_MAVLINK_BATTERY_STATUS_PERIOD_MS",
    ):
        _validate_int_range(
            kconf, symbol, MAVLINK_TELEMETRY_PERIOD_MIN_MS, MAVLINK_TELEMETRY_PERIOD_MAX_MS
        )
    _validate_int_range(
        kconf,
        "ESP32_MAVLINK_RX_READ_CHUNK_SIZE",
        MAVLINK_RX_READ_CHUNK_MIN,
        MAVLINK_RX_READ_CHUNK_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_MAVLINK_HEARTBEAT_DEADLINE_MS",
        MAVLINK_HEARTBEAT_DEADLINE_MIN_MS,
        MAVLINK_HEARTBEAT_DEADLINE_MAX_MS,
    )
    for symbol in (
        "ESP32_MAVLINK_GPS_START_DELAY_MS",
        "ESP32_MAVLINK_ATTITUDE_START_DELAY_MS",
        "ESP32_MAVLINK_GLOBAL_POSITION_START_DELAY_MS",
        "ESP32_MAVLINK_BATTERY_STATUS_START_DELAY_MS",
    ):
        _validate_int_range(
            kconf, symbol, MAVLINK_START_DELAY_MIN_MS, MAVLINK_START_DELAY_MAX_MS
        )
    _validate_int_range(
        kconf,
        "ESP32_RCRX_UART_RX_BUFFER_SIZE",
        UART_BUFFER_SIZE_MIN,
        UART_BUFFER_SIZE_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_RCRX_UART_TX_BUFFER_SIZE",
        UART_BUFFER_SIZE_MIN,
        UART_BUFFER_SIZE_MAX,
    )
    wifi_ssid = _sym_str(kconf, "ESP32_WIFI_AP_SSID")
    wifi_password = _sym_str(kconf, "ESP32_WIFI_AP_PASSWORD")
    if not WIFI_AP_SSID_MIN_LEN <= len(wifi_ssid) <= WIFI_AP_SSID_MAX_LEN:
        raise ValueError(
            "ESP32_WIFI_AP_SSID must be between "
            f"{WIFI_AP_SSID_MIN_LEN} and {WIFI_AP_SSID_MAX_LEN} characters"
        )
    if len(wifi_password) > WIFI_AP_PASSWORD_MAX_LEN:
        raise ValueError(
            f"ESP32_WIFI_AP_PASSWORD must be at most {WIFI_AP_PASSWORD_MAX_LEN} characters"
        )
    if 0 < len(wifi_password) < WIFI_AP_PASSWORD_MIN_LEN:
        raise ValueError(
            "ESP32_WIFI_AP_PASSWORD must be empty or at least "
            f"{WIFI_AP_PASSWORD_MIN_LEN} characters"
        )
    _validate_int_range(
        kconf, "ESP32_WIFI_AP_CHANNEL", WIFI_AP_CHANNEL_MIN, WIFI_AP_CHANNEL_MAX
    )
    _validate_int_range(
        kconf,
        "ESP32_WIFI_AP_MAX_CONNECTIONS",
        WIFI_AP_MAX_CONNECTIONS_MIN,
        WIFI_AP_MAX_CONNECTIONS_MAX,
    )
    beacon_interval_tu = _sym_int(kconf, "ESP32_WIFI_AP_BEACON_INTERVAL_TU")
    if not WIFI_AP_BEACON_INTERVAL_MIN_TU <= beacon_interval_tu <= WIFI_AP_BEACON_INTERVAL_MAX_TU:
        raise ValueError(
            "ESP32_WIFI_AP_BEACON_INTERVAL_TU must be in the range "
            f"{WIFI_AP_BEACON_INTERVAL_MIN_TU}..{WIFI_AP_BEACON_INTERVAL_MAX_TU}"
        )
    if beacon_interval_tu % 100 != 0:
        raise ValueError("ESP32_WIFI_AP_BEACON_INTERVAL_TU must be a multiple of 100")
    if _sym_bool(kconf, "ESP32_WIFI_PMF_REQUIRED") and not _sym_bool(
        kconf, "ESP32_WIFI_PMF_CAPABLE"
    ):
        raise ValueError("ESP32_WIFI_PMF_REQUIRED requires ESP32_WIFI_PMF_CAPABLE")
    _validate_int_range(
        kconf,
        "ESP32_PROGRAMMER_RESET_PULSE_MS",
        PROGRAMMER_RESET_PULSE_MIN_MS,
        PROGRAMMER_RESET_PULSE_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_PROGRAMMER_BOOT_SETTLE_MS",
        PROGRAMMER_BOOT_SETTLE_MIN_MS,
        PROGRAMMER_BOOT_SETTLE_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_PROGRAMMER_SYNC_TIMEOUT_MS",
        PROGRAMMER_SYNC_TIMEOUT_MIN_MS,
        PROGRAMMER_SYNC_TIMEOUT_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_PROGRAMMER_SYNC_RETRIES",
        PROGRAMMER_SYNC_RETRIES_MIN,
        PROGRAMMER_SYNC_RETRIES_MAX,
    )
    if _sym_bool(kconf, "ESP32_BUTTON_PULLUP") and _sym_bool(
        kconf, "ESP32_BUTTON_PULLDOWN"
    ):
        raise ValueError("ESP32 button pull-up and pull-down cannot both be enabled")


def _emit_runtime_header(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> str:
    fclink_uart_baud_rate = _choice_value(kconf, FCLINK_UART_BAUD_RATE_CHOICES)
    fclink_uart_parity = _choice_value(kconf, FCLINK_UART_PARITY_CHOICES)
    rcrx_uart_baud_rate = _choice_value(kconf, RCRX_UART_BAUD_RATE_CHOICES)
    rcrx_uart_parity = _choice_value(kconf, RCRX_UART_PARITY_CHOICES)
    return AUTOGEN_WARNING.format(source=source.name) + textwrap.dedent(
        f"""\
            #pragma once

            #include "hal/gpio_types.h"
            #include "button.hpp"
            #include "buzzer.hpp"
            #include "fc_link.hpp"
            #include "led.hpp"
            #include "mavlink.hpp"
            #include "programmer.hpp"
            #include "uart.hpp"
            #include "wifi.hpp"

            struct PinMap {{
                gpio_num_t led;
                gpio_num_t button;
                gpio_num_t buzzer;
                gpio_num_t fclink_uart_tx;
                gpio_num_t fclink_uart_rx;
                gpio_num_t rcrx_uart_tx;
                gpio_num_t rcrx_uart_rx;
                gpio_num_t programmer_boot0;
                gpio_num_t programmer_nrst;
            }};

            inline constexpr PinMap kPinMap = {{
                .led = static_cast<gpio_num_t>({_sym_int(kconf, "ESP32_PINMAP_LED_GPIO_NUM")}),
                .button = static_cast<gpio_num_t>({_sym_int(kconf, "ESP32_PINMAP_BUTTON_GPIO_NUM")}),
                .buzzer = static_cast<gpio_num_t>({_sym_int(kconf, "ESP32_PINMAP_BUZZER_GPIO_NUM")}),
                .fclink_uart_tx = static_cast<gpio_num_t>({_sym_int(kconf, "ESP32_PINMAP_FCLINK_UART_TX_GPIO_NUM")}),
                .fclink_uart_rx = static_cast<gpio_num_t>({_sym_int(kconf, "ESP32_PINMAP_FCLINK_UART_RX_GPIO_NUM")}),
                .rcrx_uart_tx = static_cast<gpio_num_t>({_sym_int(kconf, "ESP32_PINMAP_RCRX_UART_TX_GPIO_NUM")}),
                .rcrx_uart_rx = static_cast<gpio_num_t>({_sym_int(kconf, "ESP32_PINMAP_RCRX_UART_RX_GPIO_NUM")}),
                .programmer_boot0 = static_cast<gpio_num_t>({_sym_int(kconf, "ESP32_PINMAP_PROGRAMMER_BOOT0_GPIO_NUM")}),
                .programmer_nrst = static_cast<gpio_num_t>({_sym_int(kconf, "ESP32_PINMAP_PROGRAMMER_NRST_GPIO_NUM")}),
            }};

            inline constexpr Button::Config kButtonConfig = {{
                .pin = kPinMap.button,
                .active_low = {"true" if _sym_bool(kconf, "ESP32_BUTTON_ACTIVE_LOW") else "false"},
                .pullup = {"true" if _sym_bool(kconf, "ESP32_BUTTON_PULLUP") else "false"},
                .pulldown = {"true" if _sym_bool(kconf, "ESP32_BUTTON_PULLDOWN") else "false"},
                .debounce_ms = {_sym_int(kconf, "ESP32_BUTTON_DEBOUNCE_MS")},
                .long_press_ms = {_sym_int(kconf, "ESP32_BUTTON_LONG_PRESS_MS")},
            }};

            inline constexpr LED::Config kLedConfig = {{
                .pin = kPinMap.led,
                .active_low = {"true" if _sym_bool(kconf, "ESP32_LED_ACTIVE_LOW") else "false"},
            }};

            inline constexpr Buzzer::Config kBuzzerConfig = {{
                .pin = kPinMap.buzzer,
                .active_low = {"true" if _sym_bool(kconf, "ESP32_BUZZER_ACTIVE_LOW") else "false"},
            }};

            inline constexpr UartConfig kFcLinkUartConfig = {{
                .tx_gpio = kPinMap.fclink_uart_tx,
                .rx_gpio = kPinMap.fclink_uart_rx,
                .baud_rate = {fclink_uart_baud_rate},
                .parity = {fclink_uart_parity},
                .rx_buf = {_sym_int(kconf, "ESP32_FCLINK_UART_RX_BUFFER_SIZE")},
                .tx_buf = {_sym_int(kconf, "ESP32_FCLINK_UART_TX_BUFFER_SIZE")},
            }};

            inline constexpr UartConfig kRcRxUartConfig = {{
                .tx_gpio = kPinMap.rcrx_uart_tx,
                .rx_gpio = kPinMap.rcrx_uart_rx,
                .baud_rate = {rcrx_uart_baud_rate},
                .parity = {rcrx_uart_parity},
                .rx_buf = {_sym_int(kconf, "ESP32_RCRX_UART_RX_BUFFER_SIZE")},
                .tx_buf = {_sym_int(kconf, "ESP32_RCRX_UART_TX_BUFFER_SIZE")},
            }};

            inline constexpr FcLink::Config kFcLinkConfig = {{
                .telemetry_rate_hz = {_sym_int(kconf, "ESP32_FCLINK_TELEMETRY_RATE_HZ")},
                .handshake_timeout_ms = {_sym_int(kconf, "ESP32_FCLINK_HANDSHAKE_TIMEOUT_MS")},
                .handshake_retry_period_ms = {_sym_int(kconf, "ESP32_FCLINK_HANDSHAKE_RETRY_PERIOD_MS")},
                .rx_read_chunk_size = {_sym_int(kconf, "ESP32_FCLINK_RX_READ_CHUNK_SIZE")},
                .rx_queue_depth = {_sym_int(kconf, "ESP32_FCLINK_RX_QUEUE_DEPTH")},
            }};

            inline constexpr Programmer::Config kProgrammerConfig = {{
                .boot0_pin = kPinMap.programmer_boot0,
                .nrst_pin = kPinMap.programmer_nrst,
                .reset_pulse_ms = {_sym_int(kconf, "ESP32_PROGRAMMER_RESET_PULSE_MS")},
                .boot_settle_ms = {_sym_int(kconf, "ESP32_PROGRAMMER_BOOT_SETTLE_MS")},
                .sync_timeout_ms = {_sym_int(kconf, "ESP32_PROGRAMMER_SYNC_TIMEOUT_MS")},
                .sync_retries = {_sym_int(kconf, "ESP32_PROGRAMMER_SYNC_RETRIES")},
            }};

            inline constexpr WifiController::Config kWifiConfig = {{
                .ap =
                    {{
                        .ssid = {_cpp_string_literal(_sym_str(kconf, "ESP32_WIFI_AP_SSID"))},
                        .password = {_cpp_string_literal(_sym_str(kconf, "ESP32_WIFI_AP_PASSWORD"))},
                        .channel = {_sym_int(kconf, "ESP32_WIFI_AP_CHANNEL")},
                        .max_connections = {_sym_int(kconf, "ESP32_WIFI_AP_MAX_CONNECTIONS")},
                        .beacon_interval_tu = {_sym_int(kconf, "ESP32_WIFI_AP_BEACON_INTERVAL_TU")},
                        .hidden = {"true" if _sym_bool(kconf, "ESP32_WIFI_AP_HIDDEN") else "false"},
                    }},
                .pmf =
                    {{
                        .capable = {"true" if _sym_bool(kconf, "ESP32_WIFI_PMF_CAPABLE") else "false"},
                        .required = {"true" if _sym_bool(kconf, "ESP32_WIFI_PMF_REQUIRED") else "false"},
                    }},
                .power_save = {_choice_value(kconf, WIFI_POWER_SAVE_CHOICES)},
            }};

            inline constexpr Mavlink::Config kMavlinkConfig = {{
                .identity =
                    {{
                        .sysid = {_sym_int(kconf, "ESP32_MAVLINK_SYSID")},
                        .compid = {_sym_int(kconf, "ESP32_MAVLINK_COMPID")},
                    }},
                .rx =
                    {{
                        .read_chunk_size = {_sym_int(kconf, "ESP32_MAVLINK_RX_READ_CHUNK_SIZE")},
                    }},
                .tx =
                    {{
                        .periods =
                            {{
                                .hb_ms = {_sym_int(kconf, "ESP32_MAVLINK_HEARTBEAT_PERIOD_MS")},
                                .gps_ms = {_sym_int(kconf, "ESP32_MAVLINK_GPS_PERIOD_MS")},
                                .att_ms = {_sym_int(kconf, "ESP32_MAVLINK_ATTITUDE_PERIOD_MS")},
                                .gpos_ms = {_sym_int(kconf, "ESP32_MAVLINK_GLOBAL_POSITION_PERIOD_MS")},
                                .batt_ms = {_sym_int(kconf, "ESP32_MAVLINK_BATTERY_STATUS_PERIOD_MS")},
                            }},
                        .schedule =
                            {{
                                .hb_deadline_ms = {_sym_int(kconf, "ESP32_MAVLINK_HEARTBEAT_DEADLINE_MS")},
                                .gps_start_delay_ms = {_sym_int(kconf, "ESP32_MAVLINK_GPS_START_DELAY_MS")},
                                .att_start_delay_ms = {_sym_int(kconf, "ESP32_MAVLINK_ATTITUDE_START_DELAY_MS")},
                                .gpos_start_delay_ms = {_sym_int(kconf, "ESP32_MAVLINK_GLOBAL_POSITION_START_DELAY_MS")},
                                .batt_start_delay_ms = {_sym_int(kconf, "ESP32_MAVLINK_BATTERY_STATUS_START_DELAY_MS")},
                            }},
                    }},
            }};
            """
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kconfig", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--runtime-out", required=True)
    args = parser.parse_args()

    kconfig_path = pathlib.Path(args.kconfig).resolve()
    config_path = pathlib.Path(args.config).resolve()
    runtime_out = pathlib.Path(args.runtime_out).resolve()

    kconf = kconfiglib.Kconfig(str(kconfig_path))
    if config_path.exists():
        kconf.load_config(str(config_path))

    _validate(kconf)

    runtime_out.parent.mkdir(parents=True, exist_ok=True)
    runtime_out.write_text(_emit_runtime_header(config_path, kconf), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
