#!/usr/bin/env python3

from __future__ import annotations

import argparse
import pathlib
import textwrap

import kconfiglib


AUTOGEN_WARNING = (
    "// This file is autogenerated. Do not modify manually.\n" "// Source: {source}\n"
)

ICM42688P_FIFO_BYTES = 2048
ICM42688P_PACKET3_BYTES = 16

SPI_PRESCALER_CHOICES = {
    "STM32_IMU_SPI_PRESCALER_DIV2": "SpiPrescaler::kDiv2",
    "STM32_IMU_SPI_PRESCALER_DIV4": "SpiPrescaler::kDiv4",
    "STM32_IMU_SPI_PRESCALER_DIV8": "SpiPrescaler::kDiv8",
    "STM32_IMU_SPI_PRESCALER_DIV16": "SpiPrescaler::kDiv16",
    "STM32_IMU_SPI_PRESCALER_DIV32": "SpiPrescaler::kDiv32",
    "STM32_IMU_SPI_PRESCALER_DIV64": "SpiPrescaler::kDiv64",
    "STM32_IMU_SPI_PRESCALER_DIV128": "SpiPrescaler::kDiv128",
    "STM32_IMU_SPI_PRESCALER_DIV256": "SpiPrescaler::kDiv256",
}

ICM20948_SPI_PRESCALER_CHOICES = {
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV2": "SpiPrescaler::kDiv2",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV4": "SpiPrescaler::kDiv4",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV8": "SpiPrescaler::kDiv8",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV16": "SpiPrescaler::kDiv16",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV32": "SpiPrescaler::kDiv32",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV64": "SpiPrescaler::kDiv64",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV128": "SpiPrescaler::kDiv128",
    "STM32_IMU_ICM20948_SPI_PRESCALER_DIV256": "SpiPrescaler::kDiv256",
}

M9N_BAUD_RATE_CHOICES = {
    "STM32_GPS_M9N_BAUD_9600": "M9N::BaudRate::k9600",
    "STM32_GPS_M9N_BAUD_19200": "M9N::BaudRate::k19200",
    "STM32_GPS_M9N_BAUD_38400": "M9N::BaudRate::k38400",
    "STM32_GPS_M9N_BAUD_57600": "M9N::BaudRate::k57600",
    "STM32_GPS_M9N_BAUD_115200": "M9N::BaudRate::k115200",
    "STM32_GPS_M9N_BAUD_230400": "M9N::BaudRate::k230400",
    "STM32_GPS_M9N_BAUD_460800": "M9N::BaudRate::k460800",
    "STM32_GPS_M9N_BAUD_921600": "M9N::BaudRate::k921600",
}

M9N_DYNAMIC_MODEL_CHOICES = {
    "STM32_GPS_M9N_DYN_MODEL_PORTABLE": "M9N::DynamicModel::kPortable",
    "STM32_GPS_M9N_DYN_MODEL_STATIONARY": "M9N::DynamicModel::kStationary",
    "STM32_GPS_M9N_DYN_MODEL_PEDESTRIAN": "M9N::DynamicModel::kPedestrian",
    "STM32_GPS_M9N_DYN_MODEL_AUTOMOTIVE": "M9N::DynamicModel::kAutomotive",
    "STM32_GPS_M9N_DYN_MODEL_SEA": "M9N::DynamicModel::kSea",
    "STM32_GPS_M9N_DYN_MODEL_AIRBORNE_1G": "M9N::DynamicModel::kAirborne1g",
    "STM32_GPS_M9N_DYN_MODEL_AIRBORNE_2G": "M9N::DynamicModel::kAirborne2g",
    "STM32_GPS_M9N_DYN_MODEL_AIRBORNE_4G": "M9N::DynamicModel::kAirborne4g",
    "STM32_GPS_M9N_DYN_MODEL_WRIST": "M9N::DynamicModel::kWrist",
    "STM32_GPS_M9N_DYN_MODEL_BIKE": "M9N::DynamicModel::kBike",
}

M9N_TIMEGRID_CHOICES = {
    "STM32_GPS_M9N_TP1_TIMEGRID_UTC": "M9N::TimeGrid::kUtc",
    "STM32_GPS_M9N_TP1_TIMEGRID_GPS": "M9N::TimeGrid::kGps",
    "STM32_GPS_M9N_TP1_TIMEGRID_GLONASS": "M9N::TimeGrid::kGlonass",
    "STM32_GPS_M9N_TP1_TIMEGRID_BEIDOU": "M9N::TimeGrid::kBeiDou",
    "STM32_GPS_M9N_TP1_TIMEGRID_GALILEO": "M9N::TimeGrid::kGalileo",
}

ODR_CHOICES = {
    "STM32_IMU_GYRO_ODR_32KHZ": "Icm42688pReg::Odr::k32kHz",
    "STM32_IMU_GYRO_ODR_16KHZ": "Icm42688pReg::Odr::k16kHz",
    "STM32_IMU_GYRO_ODR_8KHZ": "Icm42688pReg::Odr::k8kHz",
    "STM32_IMU_GYRO_ODR_4KHZ": "Icm42688pReg::Odr::k4kHz",
    "STM32_IMU_GYRO_ODR_2KHZ": "Icm42688pReg::Odr::k2kHz",
    "STM32_IMU_GYRO_ODR_1KHZ": "Icm42688pReg::Odr::k1kHz",
    "STM32_IMU_GYRO_ODR_500HZ": "Icm42688pReg::Odr::k500Hz",
    "STM32_IMU_GYRO_ODR_200HZ": "Icm42688pReg::Odr::k200Hz",
    "STM32_IMU_GYRO_ODR_100HZ": "Icm42688pReg::Odr::k100Hz",
    "STM32_IMU_GYRO_ODR_50HZ": "Icm42688pReg::Odr::k50Hz",
    "STM32_IMU_GYRO_ODR_25HZ": "Icm42688pReg::Odr::k25Hz",
    "STM32_IMU_GYRO_ODR_12_5HZ": "Icm42688pReg::Odr::k12_5Hz",
}

ACCEL_ODR_CHOICES = {
    key.replace("GYRO", "ACCEL"): value for key, value in ODR_CHOICES.items()
}

GYRO_FS_CHOICES = {
    "STM32_IMU_GYRO_FS_2000DPS": "Icm42688pReg::GyroFs::k2000dps",
    "STM32_IMU_GYRO_FS_1000DPS": "Icm42688pReg::GyroFs::k1000dps",
    "STM32_IMU_GYRO_FS_500DPS": "Icm42688pReg::GyroFs::k500dps",
    "STM32_IMU_GYRO_FS_250DPS": "Icm42688pReg::GyroFs::k250dps",
    "STM32_IMU_GYRO_FS_125DPS": "Icm42688pReg::GyroFs::k125dps",
    "STM32_IMU_GYRO_FS_62_5DPS": "Icm42688pReg::GyroFs::k62_5dps",
    "STM32_IMU_GYRO_FS_31_25DPS": "Icm42688pReg::GyroFs::k31_25dps",
    "STM32_IMU_GYRO_FS_15_625DPS": "Icm42688pReg::GyroFs::k15_625dps",
}

ACCEL_FS_CHOICES = {
    "STM32_IMU_ACCEL_FS_16G": "Icm42688pReg::AccelFs::k16g",
    "STM32_IMU_ACCEL_FS_8G": "Icm42688pReg::AccelFs::k8g",
    "STM32_IMU_ACCEL_FS_4G": "Icm42688pReg::AccelFs::k4g",
    "STM32_IMU_ACCEL_FS_2G": "Icm42688pReg::AccelFs::k2g",
}


def _sym(kconf: kconfiglib.Kconfig, name: str) -> kconfiglib.Symbol:
    sym = kconf.syms.get(name)
    if sym is None:
        raise ValueError(f"missing Kconfig symbol '{name}'")
    return sym


def _sym_int(kconf: kconfiglib.Kconfig, name: str) -> int:
    return int(_sym(kconf, name).str_value)


def _sym_bool(kconf: kconfiglib.Kconfig, name: str) -> bool:
    return _sym(kconf, name).tri_value == 2


def _choice_value(kconf: kconfiglib.Kconfig, mapping: dict[str, str]) -> str:
    for symbol_name, value in mapping.items():
        if _sym_bool(kconf, symbol_name):
            return value
    raise ValueError(f"no selected symbol in choice {tuple(mapping.keys())}")


def _imu_fifo_capacity_records() -> int:
    return ICM42688P_FIFO_BYTES // ICM42688P_PACKET3_BYTES


def _validate(kconf: kconfiglib.Kconfig) -> None:
    watermark_records = _sym_int(kconf, "STM32_IMU_FIFO_WATERMARK_RECORDS")
    hardware_max_records = _imu_fifo_capacity_records()
    if watermark_records <= 0:
        raise ValueError("CONFIG_STM32_IMU_FIFO_WATERMARK_RECORDS must be > 0")
    if watermark_records > hardware_max_records:
        raise ValueError(
            "CONFIG_STM32_IMU_FIFO_WATERMARK_RECORDS exceeds ICM42688P FIFO capacity "
            f"({watermark_records} > {hardware_max_records})"
        )


def _emit_limits_header(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> str:
    max_records = _sym_int(kconf, "STM32_IMU_FIFO_WATERMARK_RECORDS")
    return AUTOGEN_WARNING.format(source=source.name) + textwrap.dedent(
        f"""\
            #pragma once

            #include <cstdint>

            namespace stm32_limits {{

            inline constexpr uint16_t kIcm42688pMaxWatermarkRecords = {max_records};

            }} // namespace stm32_limits
            """
    )


def _emit_runtime_header(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> str:
    spi_prescaler = _choice_value(kconf, SPI_PRESCALER_CHOICES)
    icm20948_spi_prescaler = _choice_value(kconf, ICM20948_SPI_PRESCALER_CHOICES)
    m9n_baud_rate = _choice_value(kconf, M9N_BAUD_RATE_CHOICES)
    m9n_dynamic_model = _choice_value(kconf, M9N_DYNAMIC_MODEL_CHOICES)
    m9n_timegrid = _choice_value(kconf, M9N_TIMEGRID_CHOICES)
    gyro_odr = _choice_value(kconf, ODR_CHOICES)
    accel_odr = _choice_value(kconf, ACCEL_ODR_CHOICES)
    gyro_fs = _choice_value(kconf, GYRO_FS_CHOICES)
    accel_fs = _choice_value(kconf, ACCEL_FS_CHOICES)

    return AUTOGEN_WARNING.format(source=source.name) + textwrap.dedent(
        f"""\
            #pragma once

            #include "button.hpp"
            #include "icm42688p.hpp"
            #include "icm20948.hpp"
            #include "m9n.hpp"
            #include "spi.hpp"
            #include "stm32_limits.hpp"

            inline constexpr Icm42688p::Config kIcm42688pConfig = {{
                .spi_prescaler = {spi_prescaler},
                .rates = {{
                    .gyro = {gyro_odr},
                    .accel = {accel_odr},
                }},
                .fs = {{
                    .gyro = {gyro_fs},
                    .accel = {accel_fs},
                }},
                .ui_filter = {{
                    .gyro_bw = {_sym_int(kconf, "STM32_IMU_UI_FILTER_GYRO_BW")},
                    .accel_bw = {_sym_int(kconf, "STM32_IMU_UI_FILTER_ACCEL_BW")},
                    .gyro_cfg1 = {_sym_int(kconf, "STM32_IMU_UI_FILTER_GYRO_CFG1")},
                    .accel_cfg1 = {_sym_int(kconf, "STM32_IMU_UI_FILTER_ACCEL_CFG1")},
                }},
                .notch = {{
                    .freq_hz = {float(_sym_int(kconf, "STM32_IMU_NOTCH_FREQ_HZ")):.6f}f,
                    .bw_idx = {_sym_int(kconf, "STM32_IMU_NOTCH_BW_IDX")},
                    .enabled = {"true" if _sym_bool(kconf, "STM32_IMU_NOTCH_ENABLED") else "false"},
                }},
                .gyro_aaf = {{
                    .dis = {"true" if _sym_bool(kconf, "STM32_IMU_GYRO_AAF_DISABLE") else "false"},
                    .delt = {_sym_int(kconf, "STM32_IMU_GYRO_AAF_DELT")},
                    .delt_sqr = {_sym_int(kconf, "STM32_IMU_GYRO_AAF_DELT_SQR")},
                    .bitshift = {_sym_int(kconf, "STM32_IMU_GYRO_AAF_BITSHIFT")},
                }},
                .accel_aaf = {{
                    .dis = {"true" if _sym_bool(kconf, "STM32_IMU_ACCEL_AAF_DISABLE") else "false"},
                    .delt = {_sym_int(kconf, "STM32_IMU_ACCEL_AAF_DELT")},
                    .delt_sqr = {_sym_int(kconf, "STM32_IMU_ACCEL_AAF_DELT_SQR")},
                    .bitshift = {_sym_int(kconf, "STM32_IMU_ACCEL_AAF_BITSHIFT")},
                }},
                .fifo = {{
                    .watermark_records = {_sym_int(kconf, "STM32_IMU_FIFO_WATERMARK_RECORDS")},
                    .hold_last = {"true" if _sym_bool(kconf, "STM32_IMU_FIFO_HOLD_LAST") else "false"},
                }},
                .calibration = {{
                    .gyro_duration_s = {_sym_int(kconf, "STM32_IMU_GYRO_CAL_DURATION_S")},
                    .gyro_timeout_s = {_sym_int(kconf, "STM32_IMU_GYRO_CAL_TIMEOUT_S")},
                    .gyro_still_threshold_raw = {_sym_int(kconf, "STM32_IMU_GYRO_CAL_STILL_THRESHOLD_RAW")},
                }},
                .recovery = {{
                    .overrun_threshold = {_sym_int(kconf, "STM32_IMU_RECOVERY_OVERRUN_THRESHOLD")},
                    .overrun_window_s = {_sym_int(kconf, "STM32_IMU_RECOVERY_OVERRUN_WINDOW_S")},
                    .fault_led_period_ms = {_sym_int(kconf, "STM32_IMU_RECOVERY_FAULT_LED_PERIOD_MS")},
                }},
            }};

            inline constexpr Icm20948::Config kIcm20948Config = {{
                .dma_buf_size = {_sym_int(kconf, "STM32_IMU_ICM20948_DMA_BUF_SIZE")},
                .fifo_size = {_sym_int(kconf, "STM32_IMU_ICM20948_FIFO_SIZE")},
                .accel = {{
                    .range = {_sym(kconf, "STM32_IMU_ICM20948_ACCEL_RANGE").str_value},
                    .dlpf_config = {_sym(kconf, "STM32_IMU_ICM20948_ACCEL_DLPF_CONFIG").str_value},
                    .sample_rate_div = {_sym_int(kconf, "STM32_IMU_ICM20948_ACCEL_SAMPLE_RATE_DIV")},
                }},
                .gyro = {{
                    .range = {_sym(kconf, "STM32_IMU_ICM20948_GYRO_RANGE").str_value},
                    .dlpf_config = {_sym(kconf, "STM32_IMU_ICM20948_GYRO_DLPF_CONFIG").str_value},
                    .sample_rate_div = {_sym_int(kconf, "STM32_IMU_ICM20948_GYRO_SAMPLE_RATE_DIV")},
                }},
                .mag_rate = {_sym(kconf, "STM32_IMU_ICM20948_MAG_RATE").str_value},
                .spi_prescaler = static_cast<uint8_t>({icm20948_spi_prescaler}),
            }};

            inline const Button::Config kButtonConfig = {{
                .pin = {{.port = USER_BTN_GPIO_PORT, .number = USER_BTN_Pin}},
                .active_low = {"true" if _sym_bool(kconf, "STM32_BUTTON_ACTIVE_LOW") else "false"},
                .debounce_ms = {_sym_int(kconf, "STM32_BUTTON_DEBOUNCE_MS")},
                .long_press_ms = {_sym_int(kconf, "STM32_BUTTON_LONG_PRESS_MS")},
            }};

            inline constexpr M9N::Config kM9nConfig = {{
                .flash_config = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_FLASH_CONFIG") else "false"},
                .baud_rate = {m9n_baud_rate},
                .protocols = {{
                    .outprot_ubx = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_PROTOCOL_UBX") else "false"},
                    .outprot_nmea = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_PROTOCOL_NMEA") else "false"},
                }},
                .messages = {{
                    .nav_pvt = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_MSG_NAV_PVT") else "false"},
                    .nav_dop = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_MSG_NAV_DOP") else "false"},
                    .nav_cov = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_MSG_NAV_COV") else "false"},
                    .nav_eoe = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_MSG_NAV_EOE") else "false"},
                }},
                .nav = {{
                    .rate_meas_ms = {_sym_int(kconf, "STM32_GPS_M9N_RATE_MEAS_MS")},
                    .dyn_model = {m9n_dynamic_model},
                }},
                .gnss = {{
                    .gps_enable = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_GNSS_GPS") else "false"},
                    .glo_enable = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_GNSS_GLO") else "false"},
                    .gal_enable = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_GNSS_GAL") else "false"},
                    .bds_enable = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_GNSS_BDS") else "false"},
                    .sbas_enable = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_GNSS_SBAS") else "false"},
                    .itfm_enable = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_GNSS_ITFM") else "false"},
                }},
                .tp1 = {{
                    .ena = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_TP1_ENA") else "false"},
                    .period = {_sym_int(kconf, "STM32_GPS_M9N_TP1_PERIOD")},
                    .len = {_sym_int(kconf, "STM32_GPS_M9N_TP1_LEN")},
                    .timegrid = {m9n_timegrid},
                    .sync_gnss = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_TP1_SYNC_GNSS") else "false"},
                    .align_to_tow = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_TP1_ALIGN_TO_TOW") else "false"},
                    .pol_rising = {"true" if _sym_bool(kconf, "STM32_GPS_M9N_TP1_POL_RISING") else "false"},
                }},
                .ack_timeout_us = {_sym_int(kconf, "STM32_GPS_M9N_ACK_TIMEOUT_US")},
            }};
            """
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kconfig", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--runtime-out", required=True)
    parser.add_argument("--limits-out", required=True)
    args = parser.parse_args()

    kconfig_path = pathlib.Path(args.kconfig).resolve()
    config_path = pathlib.Path(args.config).resolve()
    runtime_out = pathlib.Path(args.runtime_out).resolve()
    limits_out = pathlib.Path(args.limits_out).resolve()

    kconf = kconfiglib.Kconfig(str(kconfig_path))
    if config_path.exists():
        kconf.load_config(str(config_path))

    _validate(kconf)

    runtime_out.parent.mkdir(parents=True, exist_ok=True)
    limits_out.parent.mkdir(parents=True, exist_ok=True)

    limits_out.write_text(_emit_limits_header(config_path, kconf), encoding="ascii")
    runtime_out.write_text(_emit_runtime_header(config_path, kconf), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
