#!/usr/bin/env python3

# /// script
# dependencies = [
#     "jinja2",
# ]
# ///

from __future__ import annotations

import argparse
import pathlib
import tomllib
try:
    from jinja2 import Environment, FileSystemLoader, StrictUndefined
except ImportError as exc:
    raise SystemExit(
        "jinja2 is required for generate_ee_schema.py. Install it in the "
        "active Python environment."
    ) from exc


AUTOGEN_WARNING = (
    "// This file is autogenerated. Do not modify manually.\n" "// Source: {source}\n"
)
TEMPLATE_DIR = pathlib.Path(__file__).with_name("templates")


CPP_TYPE_MAP = {
    "float": "float",
    "int8_t": "int8_t",
    "uint32_t": "uint32_t",
    "uint16_t": "uint16_t",
    "uint8_t": "uint8_t",
}

# Byte sizes used for generated struct/layout calculations.
TYPE_SIZE_MAP = {
    "float": 4,
    "int8_t": 1,
    "uint32_t": 4,
    "uint16_t": 2,
    "uint8_t": 1,
}


def make_tag(tag: str) -> int:
    if len(tag) != 4:
        raise ValueError(f"tag '{tag}' must be exactly 4 ASCII characters")
    return ord(tag[0]) | (ord(tag[1]) << 8) | (ord(tag[2]) << 16) | (ord(tag[3]) << 24)


def fnv1a32(data: str) -> int:
    value = 0x811C9DC5
    for byte in data.encode("ascii"):
        value ^= byte
        value = (value * 0x01000193) & 0xFFFFFFFF
    return value


def field_context(field: dict[str, object]) -> dict[str, object]:
    field_type = str(field["type"])
    cpp_type = CPP_TYPE_MAP.get(field_type)
    if cpp_type is None:
        raise ValueError(f"unsupported field type '{field_type}'")
    name = str(field["name"])
    count = int(field.get("count", 1))
    if count <= 0:
        raise ValueError(f"field '{name}' count must be > 0")
    return {
        "cpp_type": cpp_type,
        "name": name,
        "count": count,
    }


def align_up(value: int, alignment: int) -> int:
    return (value + alignment - 1) // alignment * alignment


def struct_size(fields: list[dict[str, object]]) -> int:
    # Mirror the generated C++ layout: 3-word header, natural field alignment,
    # and final struct alignment to the largest field requirement.
    offset = 12  # magic + schema_hash + size
    max_align = 4
    for field in fields:
        field_type = str(field["type"])
        count = int(field.get("count", 1))
        field_size = TYPE_SIZE_MAP[field_type]
        field_align = field_size
        offset = align_up(offset, field_align)
        offset += field_size * count
        max_align = max(max_align, field_align)
    return align_up(offset, max_align)


def schema_string(type_name: str, fields: list[dict[str, object]]) -> str:
    parts = [type_name]
    for field in fields:
        name = str(field["name"])
        field_type = str(field["type"])
        count = int(field.get("count", 1))
        if count == 1:
            parts.append(f"{field_type} {name}")
        else:
            parts.append(f"{field_type}[{count}] {name}")
    return "|".join(parts)


def blob_context(blob: dict[str, object]) -> dict[str, object]:
    type_name = str(blob["type_name"])
    tag = str(blob["tag"])
    fields = list(blob["fields"])
    schema = schema_string(type_name, fields)
    return {
        "type_name": type_name,
        "magic_hex": f"0x{make_tag(tag):08X}u",
        "schema_hash_hex": f"0x{fnv1a32(schema):08X}u",
        "fields": [field_context(field) for field in fields],
        "expected_size": struct_size(fields),
    }


def collect_blobs(node: object) -> list[dict[str, object]]:
    # Walk the STM32 subtree and collect every schema blob definition in order.
    blobs: list[dict[str, object]] = []
    if isinstance(node, dict):
        if {"type_name", "tag", "fields"} <= set(node.keys()):
            blobs.append(node)
        for value in node.values():
            blobs.extend(collect_blobs(value))
    elif isinstance(node, list):
        for value in node:
            blobs.extend(collect_blobs(value))
    return blobs


def layout_context(blobs: list[dict[str, object]]) -> dict[str, object]:
    # Emit a packed EEPROM layout so runtime code can use generated offsets
    # instead of hardcoding them in ConfigStorage.
    entries: list[dict[str, object]] = []
    offset = 0
    for blob in blobs:
        type_name = str(blob["type_name"])
        entries.append(
            {
                "type_name": type_name,
                "offset": offset,
            }
        )
        offset += struct_size(list(blob["fields"]))
    return {
        "entries": entries,
        "total_size": offset,
    }


def _template_env() -> Environment:
    return Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )


def emit_header(source: pathlib.Path, config: dict[str, object]) -> str:
    blobs = collect_blobs(config.get("stm32", {}))
    context = {
        "autogen_warning": AUTOGEN_WARNING.format(source=source.name),
        "blobs": [blob_context(blob) for blob in blobs],
        "layout": layout_context(blobs),
    }
    return _template_env().get_template("ee_schema.hpp.j2").render(**context)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True, type=pathlib.Path)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    args = parser.parse_args()

    with args.config.open("rb") as fp:
        config = tomllib.load(fp)

    rendered = emit_header(args.config, config)
    args.out.write_text(rendered, encoding="ascii")


if __name__ == "__main__":
    main()
