#!/usr/bin/env python3

# /// script
# dependencies = [
#     "jinja2",
#     "kconfiglib",
# ]
# ///

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys

import kconfiglib

try:
    from jinja2 import Environment, FileSystemLoader, StrictUndefined
except ImportError as exc:
    raise SystemExit(
        "jinja2 is required for generate_esp32_config.py. Install it in the "
        "active Python environment."
    ) from exc


AUTOGEN_WARNING = (
    "// This file is autogenerated. Do not modify manually.\n// Source: {source}\n"
)
TEMPLATE_DIR = pathlib.Path(__file__).with_name("templates")
REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
FIRMWARE_VERSION_TOOL = REPO_ROOT / "scripts" / "generate_firmware_ver.py"

ESP32C3_GPIO_MIN = 0
ESP32C3_GPIO_MAX = 21
FCLINK_TELEMETRY_RATE_MIN = 1
FCLINK_TELEMETRY_RATE_MAX = 255
FCLINK_RC_FORWARD_RATE_MIN = 1
FCLINK_RC_FORWARD_RATE_MAX = 255
FCLINK_INVALID_PACKET_THRESHOLD_MIN = 1
FCLINK_INVALID_PACKET_THRESHOLD_MAX = 255
FCLINK_HANDSHAKE_ATTEMPTS_MIN = 1
FCLINK_HANDSHAKE_ATTEMPTS_MAX = 1000
FCLINK_HANDSHAKE_RETRY_PERIOD_MIN_MS = 1
FCLINK_HANDSHAKE_RETRY_PERIOD_MAX_MS = 1000
FCLINK_RX_QUEUE_DEPTH_MIN = 1
FCLINK_RX_QUEUE_DEPTH_MAX = 32
UART_BUFFER_SIZE_MIN = 256
UART_BUFFER_SIZE_MAX = 16384
MAVLINK_SYSID_MIN = 1
MAVLINK_SYSID_MAX = 255
MAVLINK_COMPID_MIN = 0
MAVLINK_COMPID_MAX = 255
MAVLINK_HEARTBEAT_PERIOD_MIN_MS = 1
MAVLINK_HEARTBEAT_PERIOD_MAX_MS = 60000
MAVLINK_TELEMETRY_PERIOD_MIN_MS = 0
MAVLINK_TELEMETRY_PERIOD_MAX_MS = 60000
MAVLINK_RX_READ_CHUNK_MIN = 1
MAVLINK_RX_READ_CHUNK_MAX = 256
MAVLINK_HEARTBEAT_DEADLINE_MIN_MS = 1
MAVLINK_HEARTBEAT_DEADLINE_MAX_MS = 60000
MAVLINK_START_DELAY_MIN_MS = 0
MAVLINK_START_DELAY_MAX_MS = 10000
MAVLINK_TASK_STACK_DEPTH_WORDS = 8192
MAVLINK_STACK_PANIC_THRESHOLD_BYTES = 400
PANIC_TASK_STACK_DEPTH_WORDS = 4096
WIFI_AP_SSID_MIN_LEN = 1
WIFI_AP_SSID_MAX_LEN = 32
WIFI_AP_PASSWORD_MAX_LEN = 63
WIFI_AP_PASSWORD_MIN_LEN = 8
WIFI_AP_CHANNEL_MIN = 1
WIFI_AP_CHANNEL_MAX = 13
WIFI_AP_MAX_CONNECTIONS_MIN = 1
WIFI_AP_MAX_CONNECTIONS_MAX = 10
WIFI_AP_BEACON_INTERVAL_MIN_TU = 100
WIFI_AP_BEACON_INTERVAL_MAX_TU = 60000
PROGRAMMER_RESET_PULSE_MIN_MS = 1
PROGRAMMER_RESET_PULSE_MAX_MS = 1000
PROGRAMMER_BOOT_SETTLE_MIN_MS = 1
PROGRAMMER_BOOT_SETTLE_MAX_MS = 1000
PROGRAMMER_SYNC_TIMEOUT_MIN_MS = 1
PROGRAMMER_SYNC_TIMEOUT_MAX_MS = 5000
PROGRAMMER_SYNC_RETRIES_MIN = 1
PROGRAMMER_SYNC_RETRIES_MAX = 100
PROGRAMMER_STAGING_BUFFER_BYTES = 8192
PROGRAMMER_STM32_BLOCK_BYTES = 256
PROGRAMMER_ESP32_VERIFY_CHUNK_MIN_BYTES = 1
PROGRAMMER_ESP32_VERIFY_CHUNK_MAX_BYTES = PROGRAMMER_STAGING_BUFFER_BYTES
DISPLAY_PANEL_I2C_CLOCK_MIN_HZ = 10000
DISPLAY_PANEL_I2C_CLOCK_MAX_HZ = 1000000
DISPLAY_PANEL_I2C_TIMEOUT_MIN_MS = 1
DISPLAY_PANEL_I2C_TIMEOUT_MAX_MS = 1000
DISPLAY_PANEL_I2C_SCL_WAIT_MIN_US = 0
DISPLAY_PANEL_I2C_SCL_WAIT_MAX_US = 200000
DISPLAY_PANEL_I2C_GLITCH_IGNORE_CNT_MIN = 0
DISPLAY_PANEL_I2C_GLITCH_IGNORE_CNT_MAX = 15
DISPLAY_PANEL_SETTLE_TIME_MIN_MS = 0
DISPLAY_PANEL_SETTLE_TIME_MAX_MS = 1000
DISPLAY_MANAGER_FPS_CAP_MIN = 1
DISPLAY_MANAGER_FPS_CAP_MAX = 60
TONE_PLAYER_VOLUME_MIN = 0
TONE_PLAYER_VOLUME_MAX = 10
TCP_SERVER_PORT_MIN = 1
TCP_SERVER_PORT_MAX = 65535
TCP_SERVER_BACKLOG_MIN = 1
TCP_SERVER_BACKLOG_MAX = 8
TCP_SERVER_KEEPALIVE_IDLE_MIN_S = 0
TCP_SERVER_KEEPALIVE_IDLE_MAX_S = 3600
TCP_SERVER_KEEPALIVE_INTERVAL_MIN_S = 1
TCP_SERVER_KEEPALIVE_INTERVAL_MAX_S = 3600
TCP_SERVER_KEEPALIVE_COUNT_MIN = 1
TCP_SERVER_KEEPALIVE_COUNT_MAX = 20
UDP_SERVER_UPLOAD_CAP_MIN_KBITS = 0
UDP_SERVER_UPLOAD_CAP_MAX_KBITS = 100000
UDP_SERVER_DOWNLOAD_CAP_MIN_KBITS = 0
UDP_SERVER_DOWNLOAD_CAP_MAX_KBITS = 100000
UDP_SERVER_OVERFLOW_THRESHOLD_MIN_PACKETS = 1
UDP_SERVER_OVERFLOW_THRESHOLD_MAX_PACKETS = 1000
UDP_SERVER_SHAPER_BUFFER_WINDOW_MS = 300
UDP_SERVER_SHAPER_BUFFER_MAX_BYTES = 32768
WIDGET_BOOT_TIMEOUT_MIN_S = 0
WIDGET_BOOT_TIMEOUT_MAX_S = 15
WIDGET_UI_TIMEOUT_MIN_S = 0
WIDGET_UI_TIMEOUT_MAX_S = 255

FCLINK_UART_BAUD_RATE_CHOICES = {
    "ESP32_FCLINK_UART_BAUD_9600": "9600",
    "ESP32_FCLINK_UART_BAUD_19200": "19200",
    "ESP32_FCLINK_UART_BAUD_38400": "38400",
    "ESP32_FCLINK_UART_BAUD_57600": "57600",
    "ESP32_FCLINK_UART_BAUD_115200": "115200",
    "ESP32_FCLINK_UART_BAUD_230400": "230400",
    "ESP32_FCLINK_UART_BAUD_460800": "460800",
    "ESP32_FCLINK_UART_BAUD_921600": "921600",
    "ESP32_FCLINK_UART_BAUD_1000000": "1000000",
    "ESP32_FCLINK_UART_BAUD_2000000": "2000000",
    "ESP32_FCLINK_UART_BAUD_5000000": "5000000",
}

FCLINK_UART_PARITY_CHOICES = {
    "ESP32_FCLINK_UART_PARITY_NONE": "UartParity::kNone",
    "ESP32_FCLINK_UART_PARITY_EVEN": "UartParity::kEven",
    "ESP32_FCLINK_UART_PARITY_ODD": "UartParity::kOdd",
}

RCRX_UART_BAUD_RATE_CHOICES = {
    "ESP32_RCRX_UART_BAUD_9600": "9600",
    "ESP32_RCRX_UART_BAUD_19200": "19200",
    "ESP32_RCRX_UART_BAUD_38400": "38400",
    "ESP32_RCRX_UART_BAUD_57600": "57600",
    "ESP32_RCRX_UART_BAUD_115200": "115200",
    "ESP32_RCRX_UART_BAUD_230400": "230400",
    "ESP32_RCRX_UART_BAUD_460800": "460800",
    "ESP32_RCRX_UART_BAUD_921600": "921600",
    "ESP32_RCRX_UART_BAUD_1000000": "1000000",
    "ESP32_RCRX_UART_BAUD_2000000": "2000000",
    "ESP32_RCRX_UART_BAUD_5000000": "5000000",
}

RCRX_UART_PARITY_CHOICES = {
    "ESP32_RCRX_UART_PARITY_NONE": "UartParity::kNone",
    "ESP32_RCRX_UART_PARITY_EVEN": "UartParity::kEven",
    "ESP32_RCRX_UART_PARITY_ODD": "UartParity::kOdd",
}

WIFI_POWER_SAVE_CHOICES = {
    "ESP32_WIFI_POWER_SAVE_NONE": "WIFI_PS_NONE",
    "ESP32_WIFI_POWER_SAVE_MIN_MODEM": "WIFI_PS_MIN_MODEM",
    "ESP32_WIFI_POWER_SAVE_MAX_MODEM": "WIFI_PS_MAX_MODEM",
}

UI_TRANSITION_SPEED_CHOICES = {
    "ESP32_WIDGET_UI_TRANSITION_SPEED_1X": "1",
    "ESP32_WIDGET_UI_TRANSITION_SPEED_2X": "2",
    "ESP32_WIDGET_UI_TRANSITION_SPEED_3X": "3",
}

def _sym(kconf: kconfiglib.Kconfig, name: str) -> kconfiglib.Symbol:
    sym = kconf.syms.get(name)
    if sym is None:
        raise ValueError(f"missing Kconfig symbol '{name}'")
    return sym


def _sym_int(kconf: kconfiglib.Kconfig, name: str) -> int:
    return int(_sym(kconf, name).str_value, 0)


def _sym_bool(kconf: kconfiglib.Kconfig, name: str) -> bool:
    return _sym(kconf, name).str_value == "y"


def _choice_value(kconf: kconfiglib.Kconfig, mapping: dict[str, str]) -> str:
    for symbol_name, value in mapping.items():
        if _sym_bool(kconf, symbol_name):
            return value
    raise ValueError(f"no selected symbol in choice {tuple(mapping.keys())}")


def _sym_str(kconf: kconfiglib.Kconfig, name: str) -> str:
    return _sym(kconf, name).str_value


def _cpp_string_literal(value: str) -> str:
    return json.dumps(value)


def _cpp_bool(value: bool) -> str:
    return "true" if value else "false"


def _template_env() -> Environment:
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    env.filters["cpp_bool"] = _cpp_bool
    return env


def _render_template(template_name: str, context: dict[str, object]) -> str:
    return _template_env().get_template(template_name).render(**context)


def _git_head_short_hash() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short=8", "HEAD"],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        value = result.stdout.strip().lower()
    except (OSError, subprocess.CalledProcessError):
        return "00000000"

    if len(value) < 8 or any(ch not in "0123456789abcdef" for ch in value[:8]):
        return "00000000"
    return value[:8]


def _mavlink_flight_sw_version_from_version_string(version_string: str) -> int:
    parts = version_string.strip().split(".")
    if len(parts) != 3:
        raise SystemExit(
            f"unexpected firmware version format '{version_string}'; expected X.Y.Z"
        )

    try:
        major = int(parts[0], 10)
        minor = int(parts[1], 10)
        patch = int(parts[2], 10)
    except ValueError as exc:
        raise SystemExit(
            f"unexpected firmware version format '{version_string}'; expected X.Y.Z"
        ) from exc

    if not 0 <= major <= 0xFF:
        raise SystemExit("firmware major version must fit in one byte")
    if not 0 <= minor <= 0xFF:
        raise SystemExit("firmware minor version must fit in one byte")
    if not 0 <= patch <= 0xFF:
        raise SystemExit("firmware patch version must fit in one byte")

    return (major << 24) | (minor << 16) | (patch << 8)


def _firmware_version_string() -> str:
    try:
        result = subprocess.run(
            [sys.executable, str(FIRMWARE_VERSION_TOOL)],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except OSError as exc:
        raise SystemExit(
            "scripts/generate_firmware_ver.py is required to resolve the MAVLink "
            "firmware version"
        ) from exc
    except subprocess.CalledProcessError as exc:
        stderr = exc.stderr.strip()
        message = stderr or exc.stdout.strip() or "firmware version tool failed"
        raise SystemExit(message) from exc

    version_string = result.stdout.strip()
    if not version_string:
        raise SystemExit("firmware version tool returned an empty version string")
    return version_string


def _validate_gpio_num(kconf: kconfiglib.Kconfig, name: str) -> None:
    gpio_num = _sym_int(kconf, name)
    if not ESP32C3_GPIO_MIN <= gpio_num <= ESP32C3_GPIO_MAX:
        raise ValueError(
            f"{name} must be an ESP32-C3 GPIO in the range "
            f"{ESP32C3_GPIO_MIN}..{ESP32C3_GPIO_MAX}"
        )


def _validate_int_range(
    kconf: kconfiglib.Kconfig, name: str, minimum: int, maximum: int
) -> None:
    value = _sym_int(kconf, name)
    if not minimum <= value <= maximum:
        raise ValueError(f"{name} must be in the range {minimum}..{maximum}")


def _udp_shaper_buffer_bytes(cap_kbits: int) -> int:
    if cap_kbits <= 0:
        return 0
    # window_ms at cap_kbits resolves to (cap_kbits * window_ms) bits.
    window_bytes = (cap_kbits * UDP_SERVER_SHAPER_BUFFER_WINDOW_MS + 7) // 8
    return min(max(window_bytes, 1), UDP_SERVER_SHAPER_BUFFER_MAX_BYTES)


def _validate_unique_gpio_assignments(
    kconf: kconfiglib.Kconfig, names: tuple[str, ...]
) -> None:
    assigned: dict[int, str] = {}
    duplicates: list[str] = []

    for name in names:
        gpio_num = _sym_int(kconf, name)
        previous = assigned.get(gpio_num)
        if previous is None:
            assigned[gpio_num] = name
            continue
        duplicates.append(f"GPIO{gpio_num}: {previous}, {name}")

    if duplicates:
        raise ValueError(
            "duplicate ESP32 pin assignments are not allowed: " + "; ".join(duplicates)
        )


def _validate(kconf: kconfiglib.Kconfig) -> None:
    gpio_symbols = (
        "ESP32_PINMAP_LED_GPIO_NUM",
        "ESP32_PINMAP_BUTTON_GPIO_NUM",
        "ESP32_PINMAP_BUZZER_GPIO_NUM",
        "ESP32_PINMAP_FCLINK_UART_TX_GPIO_NUM",
        "ESP32_PINMAP_FCLINK_UART_RX_GPIO_NUM",
        "ESP32_PINMAP_RCRX_UART_TX_GPIO_NUM",
        "ESP32_PINMAP_RCRX_UART_RX_GPIO_NUM",
        "ESP32_PINMAP_PROGRAMMER_BOOT0_GPIO_NUM",
        "ESP32_PINMAP_PROGRAMMER_NRST_GPIO_NUM",
    )
    if _sym_bool(kconf, "ESP32_DISPLAY_PANEL_ENABLE"):
        gpio_symbols = gpio_symbols + (
            "ESP32_PINMAP_SSD1306_PANEL_I2C_SDA_GPIO_NUM",
            "ESP32_PINMAP_SSD1306_PANEL_I2C_SCL_GPIO_NUM",
        )
    for symbol in gpio_symbols:
        _validate_gpio_num(kconf, symbol)
    _validate_unique_gpio_assignments(kconf, gpio_symbols)
    _validate_int_range(
        kconf,
        "STM32_FCLINK_TELEMETRY_RATE_HZ",
        FCLINK_TELEMETRY_RATE_MIN,
        FCLINK_TELEMETRY_RATE_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_RC_FORWARD_RATE_HZ",
        FCLINK_RC_FORWARD_RATE_MIN,
        FCLINK_RC_FORWARD_RATE_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_INVALID_PACKET_THRESHOLD",
        FCLINK_INVALID_PACKET_THRESHOLD_MIN,
        FCLINK_INVALID_PACKET_THRESHOLD_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_HANDSHAKE_ATTEMPTS",
        FCLINK_HANDSHAKE_ATTEMPTS_MIN,
        FCLINK_HANDSHAKE_ATTEMPTS_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_HANDSHAKE_RETRY_PERIOD_MS",
        FCLINK_HANDSHAKE_RETRY_PERIOD_MIN_MS,
        FCLINK_HANDSHAKE_RETRY_PERIOD_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_RX_QUEUE_DEPTH",
        FCLINK_RX_QUEUE_DEPTH_MIN,
        FCLINK_RX_QUEUE_DEPTH_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_UART_RX_BUFFER_SIZE",
        UART_BUFFER_SIZE_MIN,
        UART_BUFFER_SIZE_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_FCLINK_UART_TX_BUFFER_SIZE",
        UART_BUFFER_SIZE_MIN,
        UART_BUFFER_SIZE_MAX,
    )
    _validate_int_range(
        kconf, "ESP32_MAVLINK_SYSID", MAVLINK_SYSID_MIN, MAVLINK_SYSID_MAX
    )
    _validate_int_range(
        kconf, "ESP32_MAVLINK_COMPID", MAVLINK_COMPID_MIN, MAVLINK_COMPID_MAX
    )
    _validate_int_range(
        kconf,
        "ESP32_MAVLINK_HEARTBEAT_PERIOD_MS",
        MAVLINK_HEARTBEAT_PERIOD_MIN_MS,
        MAVLINK_HEARTBEAT_PERIOD_MAX_MS,
    )
    for symbol in (
        "ESP32_MAVLINK_GPS_PERIOD_MS",
        "ESP32_MAVLINK_ATTITUDE_PERIOD_MS",
        "ESP32_MAVLINK_GLOBAL_POSITION_PERIOD_MS",
        "ESP32_MAVLINK_BATTERY_STATUS_PERIOD_MS",
        "ESP32_MAVLINK_RC_CHANNELS_PERIOD_MS",
    ):
        _validate_int_range(
            kconf,
            symbol,
            MAVLINK_TELEMETRY_PERIOD_MIN_MS,
            MAVLINK_TELEMETRY_PERIOD_MAX_MS,
        )
    for enable_symbol, value_symbol in (
        ("ESP32_MAVLINK_RC_GPS_ENABLE", "ESP32_MAVLINK_RC_GPS_PERIOD_MS"),
        ("ESP32_MAVLINK_RC_ATTITUDE_ENABLE", "ESP32_MAVLINK_RC_ATTITUDE_PERIOD_MS"),
        (
            "ESP32_MAVLINK_RC_GLOBAL_POSITION_ENABLE",
            "ESP32_MAVLINK_RC_GLOBAL_POSITION_PERIOD_MS",
        ),
        (
            "ESP32_MAVLINK_RC_BATTERY_STATUS_ENABLE",
            "ESP32_MAVLINK_RC_BATTERY_STATUS_PERIOD_MS",
        ),
    ):
        if _sym_bool(kconf, enable_symbol):
            _validate_int_range(
                kconf,
                value_symbol,
                MAVLINK_TELEMETRY_PERIOD_MIN_MS,
                MAVLINK_TELEMETRY_PERIOD_MAX_MS,
            )
    _validate_int_range(
        kconf,
        "ESP32_MAVLINK_RC_RX_READ_CHUNK_SIZE",
        MAVLINK_RX_READ_CHUNK_MIN,
        MAVLINK_RX_READ_CHUNK_MAX,
    )
    for enable_symbol, value_symbol in (
        ("ESP32_MAVLINK_RC_GPS_ENABLE", "ESP32_MAVLINK_RC_GPS_START_DELAY_MS"),
        (
            "ESP32_MAVLINK_RC_ATTITUDE_ENABLE",
            "ESP32_MAVLINK_RC_ATTITUDE_START_DELAY_MS",
        ),
        (
            "ESP32_MAVLINK_RC_GLOBAL_POSITION_ENABLE",
            "ESP32_MAVLINK_RC_GLOBAL_POSITION_START_DELAY_MS",
        ),
        (
            "ESP32_MAVLINK_RC_BATTERY_STATUS_ENABLE",
            "ESP32_MAVLINK_RC_BATTERY_STATUS_START_DELAY_MS",
        ),
    ):
        if _sym_bool(kconf, enable_symbol):
            _validate_int_range(
                kconf,
                value_symbol,
                MAVLINK_START_DELAY_MIN_MS,
                MAVLINK_START_DELAY_MAX_MS,
            )
    _validate_int_range(
        kconf,
        "ESP32_MAVLINK_HEARTBEAT_DEADLINE_MS",
        MAVLINK_HEARTBEAT_DEADLINE_MIN_MS,
        MAVLINK_HEARTBEAT_DEADLINE_MAX_MS,
    )
    for symbol in (
        "ESP32_MAVLINK_GPS_START_DELAY_MS",
        "ESP32_MAVLINK_ATTITUDE_START_DELAY_MS",
        "ESP32_MAVLINK_GLOBAL_POSITION_START_DELAY_MS",
        "ESP32_MAVLINK_BATTERY_STATUS_START_DELAY_MS",
    ):
        _validate_int_range(
            kconf, symbol, MAVLINK_START_DELAY_MIN_MS, MAVLINK_START_DELAY_MAX_MS
        )
    _validate_int_range(
        kconf,
        "ESP32_RCRX_UART_RX_BUFFER_SIZE",
        UART_BUFFER_SIZE_MIN,
        UART_BUFFER_SIZE_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_RCRX_UART_TX_BUFFER_SIZE",
        UART_BUFFER_SIZE_MIN,
        UART_BUFFER_SIZE_MAX,
    )
    wifi_ssid = _sym_str(kconf, "ESP32_WIFI_AP_SSID")
    wifi_password = _sym_str(kconf, "ESP32_WIFI_AP_PASSWORD")
    if not WIFI_AP_SSID_MIN_LEN <= len(wifi_ssid) <= WIFI_AP_SSID_MAX_LEN:
        raise ValueError(
            "ESP32_WIFI_AP_SSID must be between "
            f"{WIFI_AP_SSID_MIN_LEN} and {WIFI_AP_SSID_MAX_LEN} characters"
        )
    if len(wifi_password) > WIFI_AP_PASSWORD_MAX_LEN:
        raise ValueError(
            f"ESP32_WIFI_AP_PASSWORD must be at most {WIFI_AP_PASSWORD_MAX_LEN} characters"
        )
    if 0 < len(wifi_password) < WIFI_AP_PASSWORD_MIN_LEN:
        raise ValueError(
            "ESP32_WIFI_AP_PASSWORD must be empty or at least "
            f"{WIFI_AP_PASSWORD_MIN_LEN} characters"
        )
    _validate_int_range(
        kconf, "ESP32_WIFI_AP_CHANNEL", WIFI_AP_CHANNEL_MIN, WIFI_AP_CHANNEL_MAX
    )
    _validate_int_range(
        kconf,
        "ESP32_WIFI_AP_MAX_CONNECTIONS",
        WIFI_AP_MAX_CONNECTIONS_MIN,
        WIFI_AP_MAX_CONNECTIONS_MAX,
    )
    beacon_interval_tu = _sym_int(kconf, "ESP32_WIFI_AP_BEACON_INTERVAL_TU")
    if (
        not WIFI_AP_BEACON_INTERVAL_MIN_TU
        <= beacon_interval_tu
        <= WIFI_AP_BEACON_INTERVAL_MAX_TU
    ):
        raise ValueError(
            "ESP32_WIFI_AP_BEACON_INTERVAL_TU must be in the range "
            f"{WIFI_AP_BEACON_INTERVAL_MIN_TU}..{WIFI_AP_BEACON_INTERVAL_MAX_TU}"
        )
    if beacon_interval_tu % 100 != 0:
        raise ValueError("ESP32_WIFI_AP_BEACON_INTERVAL_TU must be a multiple of 100")
    if _sym_bool(kconf, "ESP32_WIFI_PMF_REQUIRED") and not _sym_bool(
        kconf, "ESP32_WIFI_PMF_CAPABLE"
    ):
        raise ValueError("ESP32_WIFI_PMF_REQUIRED requires ESP32_WIFI_PMF_CAPABLE")
    _validate_int_range(
        kconf,
        "ESP32_PROGRAMMER_RESET_PULSE_MS",
        PROGRAMMER_RESET_PULSE_MIN_MS,
        PROGRAMMER_RESET_PULSE_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_PROGRAMMER_BOOT_SETTLE_MS",
        PROGRAMMER_BOOT_SETTLE_MIN_MS,
        PROGRAMMER_BOOT_SETTLE_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_PROGRAMMER_SYNC_TIMEOUT_MS",
        PROGRAMMER_SYNC_TIMEOUT_MIN_MS,
        PROGRAMMER_SYNC_TIMEOUT_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_PROGRAMMER_SYNC_RETRIES",
        PROGRAMMER_SYNC_RETRIES_MIN,
        PROGRAMMER_SYNC_RETRIES_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_PROGRAMMER_VERIFY_ESP32_CHUNK_BYTES",
        PROGRAMMER_ESP32_VERIFY_CHUNK_MIN_BYTES,
        PROGRAMMER_ESP32_VERIFY_CHUNK_MAX_BYTES,
    )
    _validate_int_range(
        kconf,
        "ESP32_DISPLAY_PANEL_I2C_CLOCK_HZ",
        DISPLAY_PANEL_I2C_CLOCK_MIN_HZ,
        DISPLAY_PANEL_I2C_CLOCK_MAX_HZ,
    )
    _validate_int_range(
        kconf,
        "ESP32_DISPLAY_PANEL_I2C_TIMEOUT_MS",
        DISPLAY_PANEL_I2C_TIMEOUT_MIN_MS,
        DISPLAY_PANEL_I2C_TIMEOUT_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_DISPLAY_PANEL_I2C_SCL_WAIT_US",
        DISPLAY_PANEL_I2C_SCL_WAIT_MIN_US,
        DISPLAY_PANEL_I2C_SCL_WAIT_MAX_US,
    )
    _validate_int_range(
        kconf,
        "ESP32_DISPLAY_PANEL_I2C_GLITCH_IGNORE_CNT",
        DISPLAY_PANEL_I2C_GLITCH_IGNORE_CNT_MIN,
        DISPLAY_PANEL_I2C_GLITCH_IGNORE_CNT_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_DISPLAY_PANEL_SETTLE_TIME_MS",
        DISPLAY_PANEL_SETTLE_TIME_MIN_MS,
        DISPLAY_PANEL_SETTLE_TIME_MAX_MS,
    )
    _validate_int_range(
        kconf,
        "ESP32_DISPLAY_MANAGER_FPS_CAP",
        DISPLAY_MANAGER_FPS_CAP_MIN,
        DISPLAY_MANAGER_FPS_CAP_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_TONE_PLAYER_VOLUME",
        TONE_PLAYER_VOLUME_MIN,
        TONE_PLAYER_VOLUME_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_TCP_SERVER_CTRL_PORT",
        TCP_SERVER_PORT_MIN,
        TCP_SERVER_PORT_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_TCP_SERVER_DATA_PORT",
        TCP_SERVER_PORT_MIN,
        TCP_SERVER_PORT_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_TCP_SERVER_BACKLOG",
        TCP_SERVER_BACKLOG_MIN,
        TCP_SERVER_BACKLOG_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_TCP_SERVER_KEEPALIVE_IDLE_S",
        TCP_SERVER_KEEPALIVE_IDLE_MIN_S,
        TCP_SERVER_KEEPALIVE_IDLE_MAX_S,
    )
    _validate_int_range(
        kconf,
        "ESP32_TCP_SERVER_KEEPALIVE_INTERVAL_S",
        TCP_SERVER_KEEPALIVE_INTERVAL_MIN_S,
        TCP_SERVER_KEEPALIVE_INTERVAL_MAX_S,
    )
    _validate_int_range(
        kconf,
        "ESP32_TCP_SERVER_KEEPALIVE_COUNT",
        TCP_SERVER_KEEPALIVE_COUNT_MIN,
        TCP_SERVER_KEEPALIVE_COUNT_MAX,
    )
    if _sym_int(kconf, "ESP32_TCP_SERVER_CTRL_PORT") == _sym_int(
        kconf, "ESP32_TCP_SERVER_DATA_PORT"
    ):
        raise ValueError(
            "ESP32_TCP_SERVER_CTRL_PORT and ESP32_TCP_SERVER_DATA_PORT must differ"
        )
    _validate_int_range(
        kconf,
        "ESP32_UDP_SERVER_PORT",
        TCP_SERVER_PORT_MIN,
        TCP_SERVER_PORT_MAX,
    )
    _validate_int_range(
        kconf,
        "ESP32_UDP_SERVER_UPLOAD_CAP_KBITS",
        UDP_SERVER_UPLOAD_CAP_MIN_KBITS,
        UDP_SERVER_UPLOAD_CAP_MAX_KBITS,
    )
    _validate_int_range(
        kconf,
        "ESP32_UDP_SERVER_OVERFLOW_THRESHOLD",
        UDP_SERVER_OVERFLOW_THRESHOLD_MIN_PACKETS,
        UDP_SERVER_OVERFLOW_THRESHOLD_MAX_PACKETS,
    )
    _validate_int_range(
        kconf,
        "ESP32_UDP_SERVER_DOWNLOAD_CAP_KBITS",
        UDP_SERVER_DOWNLOAD_CAP_MIN_KBITS,
        UDP_SERVER_DOWNLOAD_CAP_MAX_KBITS,
    )
    _validate_int_range(
        kconf,
        "ESP32_WIDGET_BOOT_TIMEOUT_S",
        WIDGET_BOOT_TIMEOUT_MIN_S,
        WIDGET_BOOT_TIMEOUT_MAX_S,
    )
    _validate_int_range(
        kconf,
        "ESP32_WIDGET_UI_TIMEOUT_S",
        WIDGET_UI_TIMEOUT_MIN_S,
        WIDGET_UI_TIMEOUT_MAX_S,
    )
    if _sym_bool(kconf, "ESP32_BUTTON_PULLUP") and _sym_bool(
        kconf, "ESP32_BUTTON_PULLDOWN"
    ):
        raise ValueError("ESP32 button pull-up and pull-down cannot both be enabled")


def _runtime_context(
    source: pathlib.Path, kconf: kconfiglib.Kconfig
) -> dict[str, object]:
    return {
        "autogen_warning": AUTOGEN_WARNING.format(source=source.name),
        "pin_map": {
            "led": _sym_int(kconf, "ESP32_PINMAP_LED_GPIO_NUM"),
            "button": _sym_int(kconf, "ESP32_PINMAP_BUTTON_GPIO_NUM"),
            "buzzer": _sym_int(kconf, "ESP32_PINMAP_BUZZER_GPIO_NUM"),
            "ssd1306_panel_i2c_sda": _sym_int(
                kconf, "ESP32_PINMAP_SSD1306_PANEL_I2C_SDA_GPIO_NUM"
            ),
            "ssd1306_panel_i2c_scl": _sym_int(
                kconf, "ESP32_PINMAP_SSD1306_PANEL_I2C_SCL_GPIO_NUM"
            ),
            "fclink_uart_tx": _sym_int(kconf, "ESP32_PINMAP_FCLINK_UART_TX_GPIO_NUM"),
            "fclink_uart_rx": _sym_int(kconf, "ESP32_PINMAP_FCLINK_UART_RX_GPIO_NUM"),
            "rcrx_uart_tx": _sym_int(kconf, "ESP32_PINMAP_RCRX_UART_TX_GPIO_NUM"),
            "rcrx_uart_rx": _sym_int(kconf, "ESP32_PINMAP_RCRX_UART_RX_GPIO_NUM"),
            "programmer_boot0": _sym_int(
                kconf, "ESP32_PINMAP_PROGRAMMER_BOOT0_GPIO_NUM"
            ),
            "programmer_nrst": _sym_int(kconf, "ESP32_PINMAP_PROGRAMMER_NRST_GPIO_NUM"),
        },
        "button": {
            "active_low": _sym_bool(kconf, "ESP32_BUTTON_ACTIVE_LOW"),
            "pullup": _sym_bool(kconf, "ESP32_BUTTON_PULLUP"),
            "pulldown": _sym_bool(kconf, "ESP32_BUTTON_PULLDOWN"),
            "debounce_ms": _sym_int(kconf, "ESP32_BUTTON_DEBOUNCE_MS"),
            "long_press_ms": _sym_int(kconf, "ESP32_BUTTON_LONG_PRESS_MS"),
            "long_long_press_ms": _sym_int(kconf, "ESP32_BUTTON_LONG_LONG_PRESS_MS"),
        },
        "led": {
            "active_low": _sym_bool(kconf, "ESP32_LED_ACTIVE_LOW"),
        },
        "buzzer": {
            "active_low": _sym_bool(kconf, "ESP32_BUZZER_ACTIVE_LOW"),
        },
        "display_i2c": {
            "glitch_ignore_cnt": _sym_int(
                kconf, "ESP32_DISPLAY_PANEL_I2C_GLITCH_IGNORE_CNT"
            ),
            "xfer_timeout_ms": _sym_int(kconf, "ESP32_DISPLAY_PANEL_I2C_TIMEOUT_MS"),
            "enable_internal_pullup": _sym_bool(
                kconf, "ESP32_DISPLAY_PANEL_I2C_ENABLE_INTERNAL_PULLUP"
            ),
        },
        "display_panel": {
            "enabled": _sym_bool(kconf, "ESP32_DISPLAY_PANEL_ENABLE"),
            "settle_time_ms": _sym_int(kconf, "ESP32_DISPLAY_PANEL_SETTLE_TIME_MS"),
            "i2c_address": _sym_int(kconf, "ESP32_DISPLAY_PANEL_I2C_ADDRESS"),
            "i2c_scl_speed_hz": _sym_int(kconf, "ESP32_DISPLAY_PANEL_I2C_CLOCK_HZ"),
            "i2c_scl_wait_us": _sym_int(kconf, "ESP32_DISPLAY_PANEL_I2C_SCL_WAIT_US"),
            "invert": _sym_bool(kconf, "ESP32_DISPLAY_PANEL_INVERT"),
            "rotate_180": _sym_bool(kconf, "ESP32_DISPLAY_PANEL_ROTATE_180"),
        },
        "ui": {
            "fps_cap": _sym_int(kconf, "ESP32_DISPLAY_MANAGER_FPS_CAP"),
            "boot_logo_timeout_s": _sym_int(kconf, "ESP32_WIDGET_BOOT_TIMEOUT_S"),
            "ui_timeout_s": _sym_int(kconf, "ESP32_WIDGET_UI_TIMEOUT_S"),
            "transition_speed_x": int(
                _choice_value(kconf, UI_TRANSITION_SPEED_CHOICES)
            ),
        },
        "tone_player": {
            "volume": _sym_int(kconf, "ESP32_TONE_PLAYER_VOLUME"),
        },
        "tcp_server": {
            "ctrl_port": _sym_int(kconf, "ESP32_TCP_SERVER_CTRL_PORT"),
            "data_port": _sym_int(kconf, "ESP32_TCP_SERVER_DATA_PORT"),
            "backlog": _sym_int(kconf, "ESP32_TCP_SERVER_BACKLOG"),
            "nonblocking": _sym_bool(kconf, "ESP32_TCP_SERVER_NONBLOCKING"),
            "keepalive_idle_s": _sym_int(kconf, "ESP32_TCP_SERVER_KEEPALIVE_IDLE_S"),
            "keepalive_intvl_s": _sym_int(
                kconf, "ESP32_TCP_SERVER_KEEPALIVE_INTERVAL_S"
            ),
            "keepalive_cnt": _sym_int(kconf, "ESP32_TCP_SERVER_KEEPALIVE_COUNT"),
        },
        "udp_server": {
            "port": _sym_int(kconf, "ESP32_UDP_SERVER_PORT"),
            "nonblocking": _sym_bool(kconf, "ESP32_UDP_SERVER_NONBLOCKING"),
            "upload_cap_kbits": _sym_int(kconf, "ESP32_UDP_SERVER_UPLOAD_CAP_KBITS"),
            "download_cap_kbits": _sym_int(
                kconf, "ESP32_UDP_SERVER_DOWNLOAD_CAP_KBITS"
            ),
            "overflow_threshold": _sym_int(
                kconf, "ESP32_UDP_SERVER_OVERFLOW_THRESHOLD"
            ),
        },
        "fclink_uart": {
            "baud_rate": _choice_value(kconf, FCLINK_UART_BAUD_RATE_CHOICES),
            "parity": _choice_value(kconf, FCLINK_UART_PARITY_CHOICES),
            "rx_buf": _sym_int(kconf, "ESP32_FCLINK_UART_RX_BUFFER_SIZE"),
            "tx_buf": _sym_int(kconf, "ESP32_FCLINK_UART_TX_BUFFER_SIZE"),
        },
        "rcrx_uart": {
            "baud_rate": _choice_value(kconf, RCRX_UART_BAUD_RATE_CHOICES),
            "parity": _choice_value(kconf, RCRX_UART_PARITY_CHOICES),
            "rx_buf": _sym_int(kconf, "ESP32_RCRX_UART_RX_BUFFER_SIZE"),
            "tx_buf": _sym_int(kconf, "ESP32_RCRX_UART_TX_BUFFER_SIZE"),
        },
        "fclink": {
            "rx_queue_depth": _sym_int(kconf, "ESP32_FCLINK_RX_QUEUE_DEPTH"),
            "rc_forward_rate_hz": _sym_int(kconf, "ESP32_FCLINK_RC_FORWARD_RATE_HZ"),
            "handshake_attempts": _sym_int(kconf, "ESP32_FCLINK_HANDSHAKE_ATTEMPTS"),
            "handshake_retry_period_ms": _sym_int(
                kconf, "ESP32_FCLINK_HANDSHAKE_RETRY_PERIOD_MS"
            ),
            "invalid_packet_threshold": _sym_int(
                kconf, "ESP32_FCLINK_INVALID_PACKET_THRESHOLD"
            ),
        },
        "programmer": {
            "reset_pulse_ms": _sym_int(kconf, "ESP32_PROGRAMMER_RESET_PULSE_MS"),
            "boot_settle_ms": _sym_int(kconf, "ESP32_PROGRAMMER_BOOT_SETTLE_MS"),
            "sync_timeout_ms": _sym_int(kconf, "ESP32_PROGRAMMER_SYNC_TIMEOUT_MS"),
            "sync_retries": _sym_int(kconf, "ESP32_PROGRAMMER_SYNC_RETRIES"),
            "verify": {
                "esp32": _sym_bool(kconf, "ESP32_PROGRAMMER_VERIFY_ESP32"),
                "esp32_chunk_bytes": _sym_int(
                    kconf, "ESP32_PROGRAMMER_VERIFY_ESP32_CHUNK_BYTES"
                ),
                "stm32": _sym_bool(kconf, "ESP32_PROGRAMMER_VERIFY_STM32"),
            },
        },
        "wifi": {
            "ap": {
                "ssid": _cpp_string_literal(_sym_str(kconf, "ESP32_WIFI_AP_SSID")),
                "password": _cpp_string_literal(
                    _sym_str(kconf, "ESP32_WIFI_AP_PASSWORD")
                ),
                "channel": _sym_int(kconf, "ESP32_WIFI_AP_CHANNEL"),
                "max_connections": _sym_int(kconf, "ESP32_WIFI_AP_MAX_CONNECTIONS"),
                "beacon_interval_tu": _sym_int(
                    kconf, "ESP32_WIFI_AP_BEACON_INTERVAL_TU"
                ),
                "hidden": _sym_bool(kconf, "ESP32_WIFI_AP_HIDDEN"),
            },
            "pmf": {
                "capable": _sym_bool(kconf, "ESP32_WIFI_PMF_CAPABLE"),
                "required": _sym_bool(kconf, "ESP32_WIFI_PMF_REQUIRED"),
            },
            "power_save": _choice_value(kconf, WIFI_POWER_SAVE_CHOICES),
        },
        "mavlink": {
            "identity": {
                "sysid": _sym_int(kconf, "ESP32_MAVLINK_SYSID"),
                "compid": _sym_int(kconf, "ESP32_MAVLINK_COMPID"),
            },
            "tx": {
                "periods": {
                    "hb_ms": _sym_int(kconf, "ESP32_MAVLINK_HEARTBEAT_PERIOD_MS"),
                    "gps_ms": _sym_int(kconf, "ESP32_MAVLINK_GPS_PERIOD_MS"),
                    "att_ms": _sym_int(kconf, "ESP32_MAVLINK_ATTITUDE_PERIOD_MS"),
                    "gpos_ms": _sym_int(
                        kconf, "ESP32_MAVLINK_GLOBAL_POSITION_PERIOD_MS"
                    ),
                    "batt_ms": _sym_int(
                        kconf, "ESP32_MAVLINK_BATTERY_STATUS_PERIOD_MS"
                    ),
                    "rc_channels_ms": _sym_int(
                        kconf, "ESP32_MAVLINK_RC_CHANNELS_PERIOD_MS"
                    ),
                },
                "schedule": {
                    "hb_deadline_ms": _sym_int(
                        kconf, "ESP32_MAVLINK_HEARTBEAT_DEADLINE_MS"
                    ),
                    "gps_start_delay_ms": _sym_int(
                        kconf, "ESP32_MAVLINK_GPS_START_DELAY_MS"
                    ),
                    "att_start_delay_ms": _sym_int(
                        kconf, "ESP32_MAVLINK_ATTITUDE_START_DELAY_MS"
                    ),
                    "gpos_start_delay_ms": _sym_int(
                        kconf, "ESP32_MAVLINK_GLOBAL_POSITION_START_DELAY_MS"
                    ),
                    "batt_start_delay_ms": _sym_int(
                        kconf, "ESP32_MAVLINK_BATTERY_STATUS_START_DELAY_MS"
                    ),
                },
            },
        },
        "mavlink_rc": {
            "rx": {
                "read_chunk_size": _sym_int(
                    kconf, "ESP32_MAVLINK_RC_RX_READ_CHUNK_SIZE"
                ),
            },
            "tx": {
                "periods": {
                    "hb_ms": 1000,
                    "gps_ms": (
                        _sym_int(kconf, "ESP32_MAVLINK_RC_GPS_PERIOD_MS")
                        if _sym_bool(kconf, "ESP32_MAVLINK_RC_GPS_ENABLE")
                        else 0
                    ),
                    "att_ms": (
                        _sym_int(kconf, "ESP32_MAVLINK_RC_ATTITUDE_PERIOD_MS")
                        if _sym_bool(kconf, "ESP32_MAVLINK_RC_ATTITUDE_ENABLE")
                        else 0
                    ),
                    "gpos_ms": (
                        _sym_int(kconf, "ESP32_MAVLINK_RC_GLOBAL_POSITION_PERIOD_MS")
                        if _sym_bool(kconf, "ESP32_MAVLINK_RC_GLOBAL_POSITION_ENABLE")
                        else 0
                    ),
                    "batt_ms": (
                        _sym_int(kconf, "ESP32_MAVLINK_RC_BATTERY_STATUS_PERIOD_MS")
                        if _sym_bool(kconf, "ESP32_MAVLINK_RC_BATTERY_STATUS_ENABLE")
                        else 0
                    ),
                    "rc_channels_ms": 0,
                },
                "schedule": {
                    "hb_deadline_ms": 1500,
                    "gps_start_delay_ms": (
                        _sym_int(kconf, "ESP32_MAVLINK_RC_GPS_START_DELAY_MS")
                        if _sym_bool(kconf, "ESP32_MAVLINK_RC_GPS_ENABLE")
                        else 0
                    ),
                    "att_start_delay_ms": (
                        _sym_int(kconf, "ESP32_MAVLINK_RC_ATTITUDE_START_DELAY_MS")
                        if _sym_bool(kconf, "ESP32_MAVLINK_RC_ATTITUDE_ENABLE")
                        else 0
                    ),
                    "gpos_start_delay_ms": (
                        _sym_int(
                            kconf, "ESP32_MAVLINK_RC_GLOBAL_POSITION_START_DELAY_MS"
                        )
                        if _sym_bool(kconf, "ESP32_MAVLINK_RC_GLOBAL_POSITION_ENABLE")
                        else 0
                    ),
                    "batt_start_delay_ms": (
                        _sym_int(
                            kconf, "ESP32_MAVLINK_RC_BATTERY_STATUS_START_DELAY_MS"
                        )
                        if _sym_bool(kconf, "ESP32_MAVLINK_RC_BATTERY_STATUS_ENABLE")
                        else 0
                    ),
                },
            },
        },
    }


def _limits_context(
    source: pathlib.Path, kconf: kconfiglib.Kconfig
) -> dict[str, object]:
    git_hash = _git_head_short_hash()
    firmware_version_string = _firmware_version_string()
    return {
        "autogen_warning": AUTOGEN_WARNING.format(source=source.name),
        "display_panel": {
            "width": 72,
            "height": 40,
            "controller_width": 128,
            "column_offset": 28,
        },
        "fclink": {
            "rx_queue_depth": _sym_int(kconf, "ESP32_FCLINK_RX_QUEUE_DEPTH"),
        },
        "mavlink": {
            "max_rx_read_chunk_size": MAVLINK_RX_READ_CHUNK_MAX,
            "task_stack_depth_words": MAVLINK_TASK_STACK_DEPTH_WORDS,
            "stack_panic_threshold_bytes": MAVLINK_STACK_PANIC_THRESHOLD_BYTES,
            "sys_autostart": 4001,
            "git_hash": git_hash,
            "version_string": firmware_version_string,
            "flight_sw_version_hex": (
                f"0x{_mavlink_flight_sw_version_from_version_string(firmware_version_string):08X}u"
            ),
        },
        "panic": {
            "task_stack_depth_words": PANIC_TASK_STACK_DEPTH_WORDS,
        },
        "programmer": {
            "staging_buffer_bytes": PROGRAMMER_STAGING_BUFFER_BYTES,
            "stm32_block_bytes": PROGRAMMER_STM32_BLOCK_BYTES,
        },
        "tcp_server": {
            "event_queue_depth": 8,
            "download_buffer_bytes": 4096,
            "max_line_bytes": 160,
        },
        "udp_server": {
            "upload_buffer_bytes": _udp_shaper_buffer_bytes(
                _sym_int(kconf, "ESP32_UDP_SERVER_UPLOAD_CAP_KBITS")
            ),
            "download_buffer_bytes": _udp_shaper_buffer_bytes(
                _sym_int(kconf, "ESP32_UDP_SERVER_DOWNLOAD_CAP_KBITS")
            ),
        },
        "tone_player": {
            "pending_request_queue_depth": 5,
        },
    }


def _emit_runtime_header(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> str:
    return _render_template("esp32_config.hpp.j2", _runtime_context(source, kconf))


def _emit_limits_header(source: pathlib.Path, kconf: kconfiglib.Kconfig) -> str:
    return _render_template("esp32_limits.hpp.j2", _limits_context(source, kconf))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kconfig", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--runtime-out", required=True)
    parser.add_argument("--limits-out", required=True)
    args = parser.parse_args()

    kconfig_path = pathlib.Path(args.kconfig).resolve()
    config_path = pathlib.Path(args.config).resolve()
    runtime_out = pathlib.Path(args.runtime_out).resolve()
    limits_out = pathlib.Path(args.limits_out).resolve()

    kconf = kconfiglib.Kconfig(str(kconfig_path))
    if config_path.exists():
        kconf.load_config(str(config_path))

    _validate(kconf)

    runtime_out.parent.mkdir(parents=True, exist_ok=True)
    limits_out.parent.mkdir(parents=True, exist_ok=True)
    runtime_out.write_text(_emit_runtime_header(config_path, kconf), encoding="ascii")
    limits_out.write_text(_emit_limits_header(config_path, kconf), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
