"""Shared helpers for the per-target Kconfig → header generators.

Both `generate_stm32_config.py` and `generate_esp32_config.py` follow the
same recipe:

    parse Kconfig + .config -> validate -> render two Jinja templates

This module factors out the recipe and the per-symbol accessors so the
two generators only have to declare their own validation, context, and
template names. Helpers here are public (no underscore prefix); the
generators import them by name.

Symbol-accessor semantics are pinned here so the two targets can't drift:

  * `sym_int` uses `int(str_value, 0)` — handles both decimal and 0x hex
    Kconfig int symbols.
  * `sym_bool` uses `tri_value == 2`, the kconfiglib idiom for "set to y".
"""

from __future__ import annotations

import argparse
import json
import pathlib
from typing import Callable

import kconfiglib

try:
    from jinja2 import Environment, FileSystemLoader, StrictUndefined
except ImportError as exc:
    raise SystemExit(
        "jinja2 is required for the Kconfig header generators. Install it "
        "in the active Python environment."
    ) from exc


AUTOGEN_WARNING = (
    "// This file is autogenerated. Do not modify manually.\n"
    "// Source: {source}\n"
)
TEMPLATE_DIR = pathlib.Path(__file__).with_name("templates")


# ---- Kconfig symbol accessors --------------------------------------------

def sym(kconf: kconfiglib.Kconfig, name: str) -> kconfiglib.Symbol:
    s = kconf.syms.get(name)
    if s is None:
        raise ValueError(f"missing Kconfig symbol '{name}'")
    return s


def sym_int(kconf: kconfiglib.Kconfig, name: str) -> int:
    return int(sym(kconf, name).str_value, 0)


def sym_bool(kconf: kconfiglib.Kconfig, name: str) -> bool:
    return sym(kconf, name).tri_value == 2


def sym_str(kconf: kconfiglib.Kconfig, name: str) -> str:
    return sym(kconf, name).str_value


def sym_hex_literal(kconf: kconfiglib.Kconfig, name: str) -> str:
    """Return a Kconfig hex symbol's value normalized as `0x...`."""
    raw = sym(kconf, name).str_value
    if not raw:
        raise ValueError(f"Kconfig hex symbol '{name}' has no value")
    return raw if raw.lower().startswith("0x") else f"0x{raw}"


def choice_value(kconf: kconfiglib.Kconfig, mapping: dict[str, str]) -> str:
    """Return the rendered value for whichever boolean in `mapping` is set."""
    for symbol_name, value in mapping.items():
        if sym_bool(kconf, symbol_name):
            return value
    raise ValueError(f"no selected symbol in choice {tuple(mapping.keys())}")


# ---- C++ literal helpers --------------------------------------------------

def cpp_bool(value: bool) -> str:
    return "true" if value else "false"


def cpp_string_literal(value: str) -> str:
    """Quote `value` as a C++ string literal (using JSON escaping)."""
    return json.dumps(value)


# ---- Jinja2 environment ---------------------------------------------------

def template_env(template_dir: pathlib.Path = TEMPLATE_DIR) -> Environment:
    """Build a Jinja2 environment configured the same way for every target.

    Includes the `cpp_bool` filter pre-registered so templates can write
    `{{ flag | cpp_bool }}` without each generator wiring it themselves.
    """
    env = Environment(
        loader=FileSystemLoader(template_dir),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    env.filters["cpp_bool"] = cpp_bool
    return env


def render_template(
    env: Environment, template_name: str, context: dict[str, object]
) -> str:
    return env.get_template(template_name).render(**context)


def autogen_warning(source: pathlib.Path) -> str:
    return AUTOGEN_WARNING.format(source=source.name)


# ---- Generator runner -----------------------------------------------------

ContextFn = Callable[[pathlib.Path, kconfiglib.Kconfig], dict[str, object]]
ValidateFn = Callable[[kconfiglib.Kconfig], None]


def run(
    *,
    validate_fn: ValidateFn,
    runtime_context_fn: ContextFn,
    limits_context_fn: ContextFn,
    runtime_template_name: str,
    limits_template_name: str,
    template_dir: pathlib.Path = TEMPLATE_DIR,
) -> int:
    """Parse CLI args, load Kconfig, validate, render both templates.

    Each per-target generator declares its own validate/context callbacks
    and template names; all the boilerplate (argparse, .config loading,
    output mkdir, ASCII write) lives here.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--kconfig", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--runtime-out", required=True)
    parser.add_argument("--limits-out", required=True)
    args = parser.parse_args()

    kconfig_path = pathlib.Path(args.kconfig).resolve()
    config_path = pathlib.Path(args.config).resolve()
    runtime_out = pathlib.Path(args.runtime_out).resolve()
    limits_out = pathlib.Path(args.limits_out).resolve()

    kconf = kconfiglib.Kconfig(str(kconfig_path))
    if config_path.exists():
        kconf.load_config(str(config_path))

    validate_fn(kconf)

    env = template_env(template_dir)
    runtime_text = render_template(
        env, runtime_template_name, runtime_context_fn(config_path, kconf)
    )
    limits_text = render_template(
        env, limits_template_name, limits_context_fn(config_path, kconf)
    )

    runtime_out.parent.mkdir(parents=True, exist_ok=True)
    limits_out.parent.mkdir(parents=True, exist_ok=True)
    runtime_out.write_text(runtime_text, encoding="ascii")
    limits_out.write_text(limits_text, encoding="ascii")
    return 0
