"""Validate stm32/Core/Inc/board.hpp against the STM32F407 silicon constraints.

Catches:
  - Pins that don't exist on the F407V package.
  - (pin, AF) combos ST never published — bogus alternate-function picks
    that compile cleanly but route signals to nowhere.
  - Same physical pin claimed by two different BoardPin entries (e.g. you
    accidentally wire two peripherals to the same pad).
  - BoardPin entries defined in board.hpp but never referenced anywhere
    in the source tree (warning only — usually a leftover after refactor).
  - Names referenced as `board::kFoo` that don't exist in board.hpp
    (compiler catches this too, but we surface it earlier).

Exit codes:
  0  no errors (warnings may have been printed)
  1  at least one error

Run:
  python3 scripts/lint/check_pinmap.py
"""

from __future__ import annotations

import pathlib
import re
import sys
from dataclasses import dataclass

# pin_constraints lives at scripts/ root because it's shared with the STM32
# config generator. Add that directory to sys.path so the lint script can
# import it from its scripts/lint/ location.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from pin_constraints import PinConstraints  # noqa: E402

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
# Sources of BoardPin declarations. Hand-edited entries live in board.hpp;
# Kconfig-tunable entries are emitted into the autogenerated stm32_config.hpp
# by generate_stm32_config.py. Both reopen `namespace board`.
BOARD_HPP = REPO_ROOT / "stm32" / "Core" / "Inc" / "board.hpp"
STM32_CONFIG_HPP = REPO_ROOT / "stm32" / "Drivers" / "USER" / "inc" / "stm32_config.hpp"
DECL_SOURCES = (BOARD_HPP, STM32_CONFIG_HPP)
SEARCH_DIRS = [
    REPO_ROOT / "stm32" / "Core",
    REPO_ROOT / "stm32" / "Drivers",
    REPO_ROOT / "stm32" / "Services",
    REPO_ROOT / "scripts" / "templates",
]
SEARCH_GLOBS = ("*.cpp", "*.hpp", "*.h", "*.c", "*.j2")


# ---- board.hpp parsing ----------------------------------------------------

@dataclass
class BoardPinDecl:
    name: str          # e.g. "kSpi2Sck"
    port: str          # e.g. "PB"
    pin_numbers: list[int]  # e.g. [13]; combined entries like SPI MISO|MOSI -> [14, 15]
    af: str            # e.g. "GPIO_AF5_SPI2"; "0" for plain GPIO

# Match `inline const{,expr} BoardPin kFoo = {GPIOX, GPIO_PIN_n[ | GPIO_PIN_m], AF, IRQ};`
_DECL_RE = re.compile(
    r"""inline\s+const(?:expr)?\s+BoardPin\s+
        (?P<name>k\w+)\s*=\s*\{
            \s*(?P<port>GPIO[A-K])\s*,
            \s*(?P<pin>[A-Z0-9_|\s]+?)\s*,
            \s*(?P<af>[\w]+)\s*,
            \s*(?P<irq>\w+)\s*,?\s*
        \}\s*;""",
    re.VERBOSE,
)
_PIN_NUM_RE = re.compile(r"GPIO_PIN_(\d+)")


def parse_board_pin_decls(paths: tuple[pathlib.Path, ...]) -> list[BoardPinDecl]:
    """Extract BoardPin declarations from any number of source headers.

    Hand-edited entries live in board.hpp; autogenerated ones come from the
    runtime config header. We treat all sources equivalently.
    """
    decls: list[BoardPinDecl] = []
    for path in paths:
        if not path.exists():
            continue
        for m in _DECL_RE.finditer(path.read_text()):
            port = "P" + m.group("port").removeprefix("GPIO")
            pin_numbers = [int(n) for n in _PIN_NUM_RE.findall(m.group("pin"))]
            if not pin_numbers:
                continue
            decls.append(
                BoardPinDecl(
                    name=m.group("name"),
                    port=port,
                    pin_numbers=pin_numbers,
                    af=m.group("af").strip(),
                )
            )
    return decls


# ---- consumer scan --------------------------------------------------------

def find_referenced_names() -> set[str]:
    pat = re.compile(r"board::(k\w+)")
    seen: set[str] = set()
    for d in SEARCH_DIRS:
        for ext in SEARCH_GLOBS:
            for p in d.rglob(ext):
                try:
                    seen.update(pat.findall(p.read_text(encoding="utf-8", errors="ignore")))
                except OSError:
                    pass
    return seen


# ---- diagnostics formatting ----------------------------------------------

def _emit(level: str, msg: str) -> None:
    print(f"{level} {msg}")


def main() -> int:
    db = PinConstraints.load_default()
    decls = parse_board_pin_decls(DECL_SOURCES)
    declared = {d.name for d in decls}
    referenced = find_referenced_names()

    errors = 0
    warnings = 0

    # 1. Validate each BoardPin against the silicon.
    for d in decls:
        for n in d.pin_numbers:
            pin_id = f"{d.port}{n}"
            if not db.is_valid_pin(pin_id):
                _emit("ERROR", f"{d.name}: pin {pin_id} does not exist on STM32F407V package")
                errors += 1
                continue
            if d.af == "0":
                # Plain GPIO — pin existing on package is enough.
                continue
            af_macros = {
                af for ((p, _sig), af) in db._pin_signal_af.items() if p == pin_id
            }
            if d.af not in af_macros:
                valid = sorted(af_macros)
                _emit(
                    "ERROR",
                    f"{d.name}: ({pin_id}, {d.af}) is not a valid alternate-function "
                    f"combo per ST data. Valid AFs on {pin_id}: {valid}",
                )
                errors += 1

    # 2. Cross-pin conflicts (same physical pin claimed by ≥2 declarations).
    claims: dict[str, list[str]] = {}
    for d in decls:
        for n in d.pin_numbers:
            claims.setdefault(f"{d.port}{n}", []).append(d.name)
    for pin_id, owners in claims.items():
        if len(owners) > 1:
            _emit(
                "ERROR",
                f"pin {pin_id} is claimed by multiple BoardPin entries: {owners}. "
                f"Combine into one entry (e.g. kFooMisoMosi) or remove a duplicate.",
            )
            errors += 1

    # 3. Unknown references — board::kFoo where kFoo isn't declared.
    for name in sorted(referenced - declared):
        _emit("ERROR", f"board::{name} is referenced but not defined in board.hpp")
        errors += 1

    # 4. Unused declarations — warning only (might be intentional WIP).
    for name in sorted(declared - referenced):
        _emit("WARN ", f"board::{name} is declared but never referenced")
        warnings += 1

    # Summary
    summary = (
        f"Pin map: {len(decls)} entries, {len(claims)} unique pins, "
        f"{errors} error(s), {warnings} warning(s)"
    )
    print(summary)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
